/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.apis

import com.lowiq.jellyfish.jellyseer.models.RadarrSettings
import com.lowiq.jellyfish.jellyseer.models.ServiceRadarrRadarrIdGet200Response
import com.lowiq.jellyfish.jellyseer.models.ServiceSonarrSonarrIdGet200Response
import com.lowiq.jellyfish.jellyseer.models.SonarrSeries
import com.lowiq.jellyfish.jellyseer.models.SonarrSettings

import com.lowiq.jellyfish.jellyseer.infrastructure.*
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import io.ktor.http.ParametersBuilder

    open class ServiceApi(
    baseUrl: String = ApiClient.BASE_URL,
    httpClientEngine: HttpClientEngine? = null,
    httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
    ) : ApiClient(
        baseUrl,
        httpClientEngine,
        httpClientConfig,
    ) {

        /**
        * GET /service/radarr
        * Get non-sensitive Radarr server list
        * Returns a list of Radarr server IDs and names in a JSON object.
         * @return kotlin.collections.List<RadarrSettings>
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun serviceRadarrGet(): HttpResponse<kotlin.collections.List<RadarrSettings>> {

            val localVariableAuthNames = listOf<String>("apiKey", "cookieAuth")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/service/radarr",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /service/radarr/{radarrId}
        * Get Radarr server quality profiles and root folders
        * Returns a Radarr server&#39;s quality profile and root folder details in a JSON object.
         * @param radarrId  
         * @return ServiceRadarrRadarrIdGet200Response
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun serviceRadarrRadarrIdGet(radarrId: Long): HttpResponse<ServiceRadarrRadarrIdGet200Response> {

            val localVariableAuthNames = listOf<String>("apiKey", "cookieAuth")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/service/radarr/{radarrId}".replace("{" + "radarrId" + "}", "$radarrId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /service/sonarr
        * Get non-sensitive Sonarr server list
        * Returns a list of Sonarr server IDs and names in a JSON object.
         * @return kotlin.collections.List<SonarrSettings>
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun serviceSonarrGet(): HttpResponse<kotlin.collections.List<SonarrSettings>> {

            val localVariableAuthNames = listOf<String>("apiKey", "cookieAuth")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/service/sonarr",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /service/sonarr/lookup/{tmdbId}
        * Get series from Sonarr
        * Returns a list of series returned by searching for the name in Sonarr.
         * @param tmdbId  
         * @return kotlin.collections.List<SonarrSeries>
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun serviceSonarrLookupTmdbIdGet(tmdbId: Long): HttpResponse<kotlin.collections.List<SonarrSeries>> {

            val localVariableAuthNames = listOf<String>("apiKey", "cookieAuth")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/service/sonarr/lookup/{tmdbId}".replace("{" + "tmdbId" + "}", "$tmdbId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /service/sonarr/{sonarrId}
        * Get Sonarr server quality profiles and root folders
        * Returns a Sonarr server&#39;s quality profile and root folder details in a JSON object.
         * @param sonarrId  
         * @return ServiceSonarrSonarrIdGet200Response
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun serviceSonarrSonarrIdGet(sonarrId: Long): HttpResponse<ServiceSonarrSonarrIdGet200Response> {

            val localVariableAuthNames = listOf<String>("apiKey", "cookieAuth")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/service/sonarr/{sonarrId}".replace("{" + "sonarrId" + "}", "$sonarrId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        }
