/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.apis

import com.lowiq.jellyfish.jellyseer.models.GenresMovieGet200ResponseInner
import com.lowiq.jellyfish.jellyseer.models.GenresTvGet200ResponseInner
import com.lowiq.jellyfish.jellyseer.models.LanguagesGet200ResponseInner
import com.lowiq.jellyfish.jellyseer.models.ProductionCompany
import com.lowiq.jellyfish.jellyseer.models.RegionsGet200ResponseInner

import com.lowiq.jellyfish.jellyseer.infrastructure.*
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import io.ktor.http.ParametersBuilder

    open class TmdbApi(
    baseUrl: String = ApiClient.BASE_URL,
    httpClientEngine: HttpClientEngine? = null,
    httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
    ) : ApiClient(
        baseUrl,
        httpClientEngine,
        httpClientConfig,
    ) {

        /**
        * GET /backdrops
        * Get backdrops of trending items
        * Returns a list of backdrop image paths in a JSON array.
         * @return kotlin.collections.List<kotlin.String>
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun backdropsGet(): HttpResponse<kotlin.collections.List<kotlin.String>> {

            val localVariableAuthNames = listOf<String>()

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/backdrops",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /genres/movie
        * Get list of official TMDB movie genres
        * Returns a list of genres in a JSON array.
         * @param language  (optional)
         * @return kotlin.collections.List<GenresMovieGet200ResponseInner>
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun genresMovieGet(language: kotlin.String?): HttpResponse<kotlin.collections.List<GenresMovieGet200ResponseInner>> {

            val localVariableAuthNames = listOf<String>("apiKey", "cookieAuth")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()
            language?.apply { localVariableQuery["language"] = listOf("$language") }

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/genres/movie",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /genres/tv
        * Get list of official TMDB movie genres
        * Returns a list of genres in a JSON array.
         * @param language  (optional)
         * @return kotlin.collections.List<GenresTvGet200ResponseInner>
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun genresTvGet(language: kotlin.String?): HttpResponse<kotlin.collections.List<GenresTvGet200ResponseInner>> {

            val localVariableAuthNames = listOf<String>("apiKey", "cookieAuth")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()
            language?.apply { localVariableQuery["language"] = listOf("$language") }

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/genres/tv",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /languages
        * Languages supported by TMDB
        * Returns a list of languages in a JSON object.
         * @return kotlin.collections.List<LanguagesGet200ResponseInner>
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun languagesGet(): HttpResponse<kotlin.collections.List<LanguagesGet200ResponseInner>> {

            val localVariableAuthNames = listOf<String>("apiKey", "cookieAuth")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/languages",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /network/{networkId}
        * Get TV network details
        * Returns TV network details in a JSON object.
         * @param networkId  
         * @return ProductionCompany
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun networkNetworkIdGet(networkId: Long): HttpResponse<ProductionCompany> {

            val localVariableAuthNames = listOf<String>("apiKey", "cookieAuth")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/network/{networkId}".replace("{" + "networkId" + "}", "$networkId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /regions
        * Regions supported by TMDB
        * Returns a list of regions in a JSON object.
         * @return kotlin.collections.List<RegionsGet200ResponseInner>
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun regionsGet(): HttpResponse<kotlin.collections.List<RegionsGet200ResponseInner>> {

            val localVariableAuthNames = listOf<String>("apiKey", "cookieAuth")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/regions",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /studio/{studioId}
        * Get movie studio details
        * Returns movie studio details in a JSON object.
         * @param studioId  
         * @return ProductionCompany
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun studioStudioIdGet(studioId: Long): HttpResponse<ProductionCompany> {

            val localVariableAuthNames = listOf<String>("apiKey", "cookieAuth")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/studio/{studioId}".replace("{" + "studioId" + "}", "$studioId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        }
