targets:
  $default:
    sources:
      - lib/$lib$
      - "**/models/**.dart"
      - "**/models/**/**.dart"
      - "**/providers/**.dart"
      - "**/providers/**/**.dart"
      - lib/util/**.dart
      - lib/jellyfin/**.dart
      - "**/**_screen.dart"
      - "**/**_page.dart"
      - swagger/**
      - lib/routes/auto_router.dart
      - $package$
    builders:
      auto_route_generator:auto_router_generator:
        options:
          enable_cached_builds: true
          generate_for:
            - lib/routes/auto_router.dart
      auto_route_generator:auto_route_generator:
        options:
          enable_cached_builds: true
          generate_for:
            - "**/**_screen.dart"
            - "**/**_page.dart"
      freezed|freezed:
        options:
          copy_with: false
          equal: false
          tostring:
          generate_for:
            - "**/**.f.dart"
            - "**/**.g.dart"
      dart_mappable_builder:
        options:
          ignoreNull: true
          discriminatorKey: type
          generateMethods: [copy]
      chopper_generator:
        options:
          header: "//Generated jellyfin api code"
          include_if_null: false
      swagger_dart_code_generator:
        options:
          input_folder: "swagger/"
          output_folder: "lib/jellyfin/"
          generate_for: swagger/**
          with_converter: true
          build_only_models: false
          with_base_url: false
          include_if_null: false
          auto_apply: dependents

