name: jellyfish
description: "A new Flutter project."
publish_to: 'none'

version: 0.7.5+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8
  iconsax_plus: ^1.0.0

  # Network and HTTP
  chopper: ^8.3.0
  cached_network_image: ^3.4.1
  http: ^1.5.0
  flutter_cache_manager: ^3.4.1
  connectivity_plus: ^6.1.5

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # JSON and Serialization
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0

  # Logging
  logging: ^1.3.0

  # Internationalization
  intl: ^0.20.2

  # Local Storage
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  flutter_secure_storage: ^9.2.2

  # UI Components
  dynamic_color: ^1.8.1
  flutter_svg: ^2.2.0
  animations: ^2.0.11

  # Navigation
  auto_route: ^10.1.2
  url_launcher: ^6.3.2

  # Utility
  path: ^1.9.1
  collection: ^1.19.1
  uuid: ^4.5.1

  # Device and System
  local_auth: ^2.3.0
  package_info_plus: ^8.3.1

  # Video Player
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_libs_video: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  chopper_generator: ^8.2.0
  json_serializable: ^6.9.5
  custom_lint: ^0.7.6
  freezed: ^3.1.0
  swagger_dart_code_generator: ^3.0.3
  riverpod_generator: ^2.6.5
  auto_route_generator: ^10.2.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/
