/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param castId 
 * @param character 
 * @param creditId 
 * @param gender 
 * @param name 
 * @param order 
 * @param profilePath 
 */
@Serializable

data class Cast (

    @SerialName(value = "id")
    val id: Long? = null,

    @SerialName(value = "castId")
    val castId: Long? = null,

    @SerialName(value = "character")
    val character: kotlin.String? = null,

    @SerialName(value = "creditId")
    val creditId: kotlin.String? = null,

    @SerialName(value = "gender")
    val gender: Long? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "order")
    val order: Long? = null,

    @SerialName(value = "profilePath")
    val profilePath: kotlin.String? = null

) {


}

