/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import com.lowiq.jellyfish.jellyseer.models.Network
import com.lowiq.jellyfish.jellyseer.models.TvResult

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param page 
 * @param totalPages 
 * @param totalResults 
 * @param network 
 * @param results 
 */
@Serializable

data class DiscoverTvNetworkNetworkIdGet200Response (

    @SerialName(value = "page")
    val page: Long? = null,

    @SerialName(value = "totalPages")
    val totalPages: Long? = null,

    @SerialName(value = "totalResults")
    val totalResults: Long? = null,

    @SerialName(value = "network")
    val network: Network? = null,

    @SerialName(value = "results")
    val results: kotlin.collections.List<TvResult>? = null

) {


}

