/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param backdrops 
 * @param name 
 */
@Serializable

data class DiscoverGenresliderMovieGet200ResponseInner (

    @SerialName(value = "id")
    val id: Long? = null,

    @SerialName(value = "backdrops")
    val backdrops: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null

) {


}

