/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param name 
 * @param airDate 
 * @param episodeNumber 
 * @param overview 
 * @param productionCode 
 * @param seasonNumber 
 * @param showId 
 * @param stillPath 
 * @param voteAverage 
 * @param voteCount 
 */
@Serializable

data class Episode (

    @SerialName(value = "id")
    val id: Long? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "airDate")
    val airDate: kotlin.String? = null,

    @SerialName(value = "episodeNumber")
    val episodeNumber: Long? = null,

    @SerialName(value = "overview")
    val overview: kotlin.String? = null,

    @SerialName(value = "productionCode")
    val productionCode: kotlin.String? = null,

    @SerialName(value = "seasonNumber")
    val seasonNumber: Long? = null,

    @SerialName(value = "showId")
    val showId: Long? = null,

    @SerialName(value = "stillPath")
    val stillPath: kotlin.String? = null,

    @SerialName(value = "voteAverage")
    val voteAverage: Long? = null,

    @SerialName(value = "voteCount")
    val voteCount: Long? = null

) {


}

