/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param facebookId 
 * @param freebaseId 
 * @param freebaseMid 
 * @param imdbId 
 * @param instagramId 
 * @param tvdbId 
 * @param tvrageId 
 * @param twitterId 
 */
@Serializable

data class ExternalIds (

    @SerialName(value = "facebookId")
    val facebookId: kotlin.String? = null,

    @SerialName(value = "freebaseId")
    val freebaseId: kotlin.String? = null,

    @SerialName(value = "freebaseMid")
    val freebaseMid: kotlin.String? = null,

    @SerialName(value = "imdbId")
    val imdbId: kotlin.String? = null,

    @SerialName(value = "instagramId")
    val instagramId: kotlin.String? = null,

    @SerialName(value = "tvdbId")
    val tvdbId: Long? = null,

    @SerialName(value = "tvrageId")
    val tvrageId: Long? = null,

    @SerialName(value = "twitterId")
    val twitterId: kotlin.String? = null

) {


}

