/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import com.lowiq.jellyfish.jellyseer.models.Issue
import com.lowiq.jellyfish.jellyseer.models.PageInfo

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param pageInfo 
 * @param results 
 */
@Serializable

data class IssueGet200Response (

    @SerialName(value = "pageInfo")
    val pageInfo: PageInfo? = null,

    @SerialName(value = "results")
    val results: kotlin.collections.List<Issue>? = null

) {


}

