/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param type 
 * @param interval 
 * @param name 
 * @param nextExecutionTime 
 * @param running 
 */
@Serializable

data class Job (

    @SerialName(value = "id")
    val id: kotlin.String? = null,

    @SerialName(value = "type")
    val type: Job.Type? = null,

    @SerialName(value = "interval")
    val interval: Job.Interval? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "nextExecutionTime")
    val nextExecutionTime: kotlin.String? = null,

    @SerialName(value = "running")
    val running: kotlin.Boolean? = null

) {

    /**
     * 
     *
     * Values: process,command
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "process") process("process"),
        @SerialName(value = "command") command("command");
    }
    /**
     * 
     *
     * Values: short,long,fixed
     */
    @Serializable
    enum class Interval(val value: kotlin.String) {
        @SerialName(value = "short") short("short"),
        @SerialName(value = "long") long("long"),
        @SerialName(value = "fixed") fixed("fixed");
    }

}

