/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import com.lowiq.jellyfish.jellyseer.models.User

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param playCount7Days 
 * @param playCount30Days 
 * @param playCount 
 * @param users 
 */
@Serializable

data class MediaMediaIdWatchDataGet200ResponseData (

    @SerialName(value = "playCount7Days")
    val playCount7Days: Long? = null,

    @SerialName(value = "playCount30Days")
    val playCount30Days: Long? = null,

    @SerialName(value = "playCount")
    val playCount: Long? = null,

    @SerialName(value = "users")
    val users: kotlin.collections.List<User>? = null

) {


}

