/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param tv 
 * @param anime 
 */
@Serializable

data class MetadataSettingsSettings (

    @SerialName(value = "tv")
    val tv: MetadataSettingsSettings.Tv? = null,

    @SerialName(value = "anime")
    val anime: MetadataSettingsSettings.Anime? = null

) {

    /**
     * 
     *
     * Values: tvdb,tmdb
     */
    @Serializable
    enum class Tv(val value: kotlin.String) {
        @SerialName(value = "tvdb") tvdb("tvdb"),
        @SerialName(value = "tmdb") tmdb("tmdb");
    }
    /**
     * 
     *
     * Values: tvdb,tmdb
     */
    @Serializable
    enum class Anime(val value: kotlin.String) {
        @SerialName(value = "tvdb") tvdb("tvdb"),
        @SerialName(value = "tmdb") tmdb("tmdb");
    }

}

