/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param certification 
 * @param iso6391 
 * @param note 
 * @param releaseDate 
 * @param type 
 */
@Serializable

data class MovieDetailsReleasesResultsInnerReleaseDatesInner (

    @SerialName(value = "certification")
    val certification: kotlin.String? = null,

    @SerialName(value = "iso_639_1")
    val iso6391: kotlin.String? = null,

    @SerialName(value = "note")
    val note: kotlin.String? = null,

    @SerialName(value = "release_date")
    val releaseDate: kotlin.String? = null,

    @SerialName(value = "type")
    val type: Long? = null

) {


}

