/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param title 
 * @param url 
 * @param criticsScore 
 */
@Serializable

data class MovieMovieIdRatingscombinedGet200ResponseImdb (

    @SerialName(value = "title")
    val title: kotlin.String? = null,

    @SerialName(value = "url")
    val url: kotlin.String? = null,

    @SerialName(value = "criticsScore")
    val criticsScore: Long? = null

) {


}

