/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param enabled 
 * @param hostname 
 * @param port 
 * @param useSsl 
 * @param user 
 * @param password 
 * @param bypassFilter 
 * @param bypassLocalAddresses 
 */
@Serializable

data class NetworkSettingsProxy (

    @SerialName(value = "enabled")
    val enabled: kotlin.Boolean? = null,

    @SerialName(value = "hostname")
    val hostname: kotlin.String? = null,

    @SerialName(value = "port")
    val port: Long? = null,

    @SerialName(value = "useSsl")
    val useSsl: kotlin.Boolean? = null,

    @SerialName(value = "user")
    val user: kotlin.String? = null,

    @SerialName(value = "password")
    val password: kotlin.String? = null,

    @SerialName(value = "bypassFilter")
    val bypassFilter: kotlin.String? = null,

    @SerialName(value = "bypassLocalAddresses")
    val bypassLocalAddresses: kotlin.Boolean? = null

) {


}

