/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param enabled 
 * @param forceMinTtl 
 * @param forceMaxTtl 
 */
@Serializable

data class NetworkSettingsDnsCache (

    @SerialName(value = "enabled")
    val enabled: kotlin.Boolean? = null,

    @SerialName(value = "forceMinTtl")
    val forceMinTtl: Long? = null,

    @SerialName(value = "forceMaxTtl")
    val forceMaxTtl: Long? = null

) {


}

