/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import com.lowiq.jellyfish.jellyseer.models.MediaInfo
import com.lowiq.jellyfish.jellyseer.models.MovieResult
import com.lowiq.jellyfish.jellyseer.models.TvResult

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param mediaType 
 * @param title 
 * @param popularity 
 * @param posterPath 
 * @param backdropPath 
 * @param voteCount 
 * @param voteAverage 
 * @param genreIds 
 * @param overview 
 * @param originalLanguage 
 * @param originalTitle 
 * @param releaseDate 
 * @param adult 
 * @param video 
 * @param mediaInfo 
 * @param name 
 * @param originalName 
 * @param originCountry 
 * @param firstAirDate 
 */
@Serializable

data class PersonResultKnownForInner (

    @SerialName(value = "id")
    val id: Long,

    @SerialName(value = "mediaType")
    val mediaType: kotlin.String,

    @SerialName(value = "title")
    val title: kotlin.String,

    @SerialName(value = "popularity")
    val popularity: Long? = null,

    @SerialName(value = "posterPath")
    val posterPath: kotlin.String? = null,

    @SerialName(value = "backdropPath")
    val backdropPath: kotlin.String? = null,

    @SerialName(value = "voteCount")
    val voteCount: Long? = null,

    @SerialName(value = "voteAverage")
    val voteAverage: Long? = null,

    @SerialName(value = "genreIds")
    val genreIds: kotlin.collections.List<Long>? = null,

    @SerialName(value = "overview")
    val overview: kotlin.String? = null,

    @SerialName(value = "originalLanguage")
    val originalLanguage: kotlin.String? = null,

    @SerialName(value = "originalTitle")
    val originalTitle: kotlin.String? = null,

    @SerialName(value = "releaseDate")
    val releaseDate: kotlin.String? = null,

    @SerialName(value = "adult")
    val adult: kotlin.Boolean? = null,

    @SerialName(value = "video")
    val video: kotlin.Boolean? = null,

    @SerialName(value = "mediaInfo")
    val mediaInfo: MediaInfo? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "originalName")
    val originalName: kotlin.String? = null,

    @SerialName(value = "originCountry")
    val originCountry: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "firstAirDate")
    val firstAirDate: kotlin.String? = null

) {


}

