/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param total 
 * @param movie 
 * @param tv 
 * @param pending 
 * @param approved 
 * @param declined 
 * @param processing 
 * @param available 
 * @param completed 
 */
@Serializable

data class RequestCountGet200Response (

    @SerialName(value = "total")
    val total: Long? = null,

    @SerialName(value = "movie")
    val movie: Long? = null,

    @SerialName(value = "tv")
    val tv: Long? = null,

    @SerialName(value = "pending")
    val pending: Long? = null,

    @SerialName(value = "approved")
    val approved: Long? = null,

    @SerialName(value = "declined")
    val declined: Long? = null,

    @SerialName(value = "processing")
    val processing: Long? = null,

    @SerialName(value = "available")
    val available: Long? = null,

    @SerialName(value = "completed")
    val completed: Long? = null

) {


}

