/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import com.lowiq.jellyfish.jellyseer.models.PlexLibrary

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param running 
 * @param progress 
 * @param total 
 * @param currentLibrary 
 * @param libraries 
 */
@Serializable

data class SettingsPlexSyncGet200Response (

    @SerialName(value = "running")
    val running: kotlin.Boolean? = null,

    @SerialName(value = "progress")
    val progress: Long? = null,

    @SerialName(value = "total")
    val total: Long? = null,

    @SerialName(value = "currentLibrary")
    val currentLibrary: PlexLibrary? = null,

    @SerialName(value = "libraries")
    val libraries: kotlin.collections.List<PlexLibrary>? = null

) {


}

