/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param hostname 
 * @param port 
 * @param apiKey 
 * @param useSsl 
 * @param baseUrl 
 */
@Serializable

data class SettingsSonarrTestPostRequest (

    @SerialName(value = "hostname")
    val hostname: kotlin.String,

    @SerialName(value = "port")
    val port: Long,

    @SerialName(value = "apiKey")
    val apiKey: kotlin.String,

    @SerialName(value = "useSsl")
    val useSsl: kotlin.Boolean,

    @SerialName(value = "baseUrl")
    val baseUrl: kotlin.String? = null

) {


}

