/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param version 
 * @param totalRequests 
 * @param totalMediaItems 
 * @param tz 
 * @param appDataPath 
 */
@Serializable

data class SettingsAboutGet200Response (

    @SerialName(value = "version")
    val version: kotlin.String? = null,

    @SerialName(value = "totalRequests")
    val totalRequests: Long? = null,

    @SerialName(value = "totalMediaItems")
    val totalMediaItems: Long? = null,

    @SerialName(value = "tz")
    val tz: kotlin.String? = null,

    @SerialName(value = "appDataPath")
    val appDataPath: kotlin.String? = null

) {


}

