/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param propertySize 
 * @param imageCount 
 */
@Serializable

data class SettingsCacheGet200ResponseImageCacheTmdb (

    @SerialName(value = "size")
    val propertySize: Long? = null,

    @SerialName(value = "imageCount")
    val imageCount: Long? = null

) {


}

