/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param propertySize 
 * @param maxSize 
 * @param hits 
 * @param misses 
 * @param failures 
 * @param ipv4Fallbacks 
 * @param hitRate 
 */
@Serializable

data class SettingsCacheGet200ResponseDnsCacheStats (

    @SerialName(value = "size")
    val propertySize: Long? = null,

    @SerialName(value = "maxSize")
    val maxSize: Long? = null,

    @SerialName(value = "hits")
    val hits: Long? = null,

    @SerialName(value = "misses")
    val misses: Long? = null,

    @SerialName(value = "failures")
    val failures: Long? = null,

    @SerialName(value = "ipv4Fallbacks")
    val ipv4Fallbacks: Long? = null,

    @SerialName(value = "hitRate")
    val hitRate: Long? = null

) {


}

