/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param username 
 * @param id 
 * @param thumb 
 * @param email 
 */
@Serializable

data class SettingsJellyfinUsersGet200ResponseInner (

    @SerialName(value = "username")
    val username: kotlin.String? = null,

    @SerialName(value = "id")
    val id: kotlin.String? = null,

    @SerialName(value = "thumb")
    val thumb: kotlin.String? = null,

    @SerialName(value = "email")
    val email: kotlin.String? = null

) {


}

