/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param botUsername 
 * @param botAPI 
 * @param chatId 
 * @param messageThreadId 
 * @param sendSilently 
 */
@Serializable

data class TelegramSettingsOptions (

    @SerialName(value = "botUsername")
    val botUsername: kotlin.String? = null,

    @SerialName(value = "botAPI")
    val botAPI: kotlin.String? = null,

    @SerialName(value = "chatId")
    val chatId: kotlin.String? = null,

    @SerialName(value = "messageThreadId")
    val messageThreadId: kotlin.String? = null,

    @SerialName(value = "sendSilently")
    val sendSilently: kotlin.Boolean? = null

) {


}

