/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param name 
 * @param gender 
 * @param profilePath 
 */
@Serializable

data class TvDetailsCreatedByInner (

    @SerialName(value = "id")
    val id: Long? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "gender")
    val gender: Long? = null,

    @SerialName(value = "profilePath")
    val profilePath: kotlin.String? = null

) {


}

