/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param email 
 * @param username 
 * @param permissions 
 */
@Serializable

data class UserPostRequest (

    @SerialName(value = "email")
    val email: kotlin.String? = null,

    @SerialName(value = "username")
    val username: kotlin.String? = null,

    @SerialName(value = "permissions")
    val permissions: Long? = null

) {


}

