/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import com.lowiq.jellyfish.jellyseer.models.UserUserIdQuotaGet200ResponseMovie

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param movie 
 * @param tv 
 */
@Serializable

data class UserUserIdQuotaGet200Response (

    @SerialName(value = "movie")
    val movie: UserUserIdQuotaGet200ResponseMovie? = null,

    @SerialName(value = "tv")
    val tv: UserUserIdQuotaGet200ResponseMovie? = null

) {


}

