/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import com.lowiq.jellyfish.jellyseer.models.MediaInfo
import com.lowiq.jellyfish.jellyseer.models.User

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param tmdbId 
 * @param ratingKey 
 * @param type 
 * @param title 
 * @param media 
 * @param createdAt 
 * @param updatedAt 
 * @param requestedBy 
 */
@Serializable

data class Watchlist (

    @SerialName(value = "id")
    val id: kotlin.Int? = null,

    @SerialName(value = "tmdbId")
    val tmdbId: Long? = null,

    @SerialName(value = "ratingKey")
    val ratingKey: kotlin.String? = null,

    @SerialName(value = "type")
    val type: kotlin.String? = null,

    @SerialName(value = "title")
    val title: kotlin.String? = null,

    @SerialName(value = "media")
    val media: MediaInfo? = null,

    @SerialName(value = "createdAt")
    val createdAt: kotlin.String? = null,

    @SerialName(value = "updatedAt")
    val updatedAt: kotlin.String? = null,

    @SerialName(value = "requestedBy")
    val requestedBy: User? = null

) {


}

