/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param displayPriority 
 * @param logoPath 
 * @param id 
 * @param name 
 */
@Serializable

data class WatchProviderDetails (

    @SerialName(value = "displayPriority")
    val displayPriority: Long? = null,

    @SerialName(value = "logoPath")
    val logoPath: kotlin.String? = null,

    @SerialName(value = "id")
    val id: Long? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null

) {


}

