/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import com.lowiq.jellyfish.jellyseer.models.WatchProviderDetails

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param iso31661 
 * @param link 
 * @param buy 
 * @param flatrate 
 */
@Serializable

data class WatchProvidersInner (

    @SerialName(value = "iso_3166_1")
    val iso31661: kotlin.String? = null,

    @SerialName(value = "link")
    val link: kotlin.String? = null,

    @SerialName(value = "buy")
    val buy: kotlin.collections.List<WatchProviderDetails>? = null,

    @SerialName(value = "flatrate")
    val flatrate: kotlin.collections.List<WatchProviderDetails>? = null

) {


}

