/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.apis

import com.lowiq.jellyfish.jellyseer.models.Blacklist

import com.lowiq.jellyfish.jellyseer.infrastructure.*
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import io.ktor.http.ParametersBuilder

    open class BlacklistApi(
    baseUrl: String = ApiClient.BASE_URL,
    httpClientEngine: HttpClientEngine? = null,
    httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
    ) : ApiClient(
        baseUrl,
        httpClientEngine,
        httpClientConfig,
    ) {

        /**
        * POST /blacklist
        * Add media to blacklist
        * 
         * @param blacklist  
         * @return void
        */
        open suspend fun blacklistPost(blacklist: Blacklist): HttpResponse<Unit> {

            val localVariableAuthNames = listOf<String>("apiKey", "cookieAuth")

            val localVariableBody = blacklist

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/blacklist",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * DELETE /blacklist/{tmdbId}
        * Remove media from blacklist
        * 
         * @param tmdbId tmdbId ID 
         * @return void
        */
        open suspend fun blacklistTmdbIdDelete(tmdbId: kotlin.String): HttpResponse<Unit> {

            val localVariableAuthNames = listOf<String>("apiKey", "cookieAuth")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.DELETE,
            "/blacklist/{tmdbId}".replace("{" + "tmdbId" + "}", "$tmdbId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /blacklist/{tmdbId}
        * Get media from blacklist
        * 
         * @param tmdbId tmdbId ID 
         * @return void
        */
        open suspend fun blacklistTmdbIdGet(tmdbId: kotlin.String): HttpResponse<Unit> {

            val localVariableAuthNames = listOf<String>("apiKey", "cookieAuth")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/blacklist/{tmdbId}".replace("{" + "tmdbId" + "}", "$tmdbId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        }
