/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.apis

import com.lowiq.jellyfish.jellyseer.models.CertificationResponse
import com.lowiq.jellyfish.jellyseer.models.CertificationsMovieGet500Response
import com.lowiq.jellyfish.jellyseer.models.CertificationsTvGet500Response
import com.lowiq.jellyfish.jellyseer.models.Keyword
import com.lowiq.jellyfish.jellyseer.models.KeywordKeywordIdGet500Response
import com.lowiq.jellyfish.jellyseer.models.WatchProviderDetails
import com.lowiq.jellyfish.jellyseer.models.WatchProviderRegion

import com.lowiq.jellyfish.jellyseer.infrastructure.*
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import io.ktor.http.ParametersBuilder

    open class OtherApi(
    baseUrl: String = ApiClient.BASE_URL,
    httpClientEngine: HttpClientEngine? = null,
    httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
    ) : ApiClient(
        baseUrl,
        httpClientEngine,
        httpClientConfig,
    ) {

        /**
        * GET /certifications/movie
        * Get movie certifications
        * Returns list of movie certifications from TMDB.
         * @return CertificationResponse
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun certificationsMovieGet(): HttpResponse<CertificationResponse> {

            val localVariableAuthNames = listOf<String>("apiKey", "cookieAuth")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/certifications/movie",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /certifications/tv
        * Get TV certifications
        * Returns list of TV show certifications from TMDB.
         * @return CertificationResponse
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun certificationsTvGet(): HttpResponse<CertificationResponse> {

            val localVariableAuthNames = listOf<String>("apiKey", "cookieAuth")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/certifications/tv",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /keyword/{keywordId}
        * Get keyword
        * Returns a single keyword in JSON format. 
         * @param keywordId  
         * @return Keyword
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun keywordKeywordIdGet(keywordId: java.math.BigDecimal): HttpResponse<Keyword> {

            val localVariableAuthNames = listOf<String>("apiKey", "cookieAuth")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/keyword/{keywordId}".replace("{" + "keywordId" + "}", "$keywordId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /watchproviders/movies
        * Get watch provider movies
        * Returns a list of all available watch providers for movies. 
         * @param watchRegion  
         * @return kotlin.collections.List<WatchProviderDetails>
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun watchprovidersMoviesGet(watchRegion: kotlin.String): HttpResponse<kotlin.collections.List<WatchProviderDetails>> {

            val localVariableAuthNames = listOf<String>("apiKey", "cookieAuth")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()
            watchRegion?.apply { localVariableQuery["watchRegion"] = listOf("$watchRegion") }

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/watchproviders/movies",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /watchproviders/regions
        * Get watch provider regions
        * Returns a list of all available watch provider regions. 
         * @return kotlin.collections.List<WatchProviderRegion>
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun watchprovidersRegionsGet(): HttpResponse<kotlin.collections.List<WatchProviderRegion>> {

            val localVariableAuthNames = listOf<String>("apiKey", "cookieAuth")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/watchproviders/regions",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /watchproviders/tv
        * Get watch provider series
        * Returns a list of all available watch providers for series. 
         * @param watchRegion  
         * @return kotlin.collections.List<WatchProviderDetails>
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun watchprovidersTvGet(watchRegion: kotlin.String): HttpResponse<kotlin.collections.List<WatchProviderDetails>> {

            val localVariableAuthNames = listOf<String>("apiKey", "cookieAuth")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()
            watchRegion?.apply { localVariableQuery["watchRegion"] = listOf("$watchRegion") }

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/watchproviders/tv",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        }
