/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.apis

import com.lowiq.jellyfish.jellyseer.models.UserUserIdWatchlistGet200Response
import com.lowiq.jellyfish.jellyseer.models.Watchlist

import com.lowiq.jellyfish.jellyseer.infrastructure.*
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import io.ktor.http.ParametersBuilder

    open class WatchlistApi(
    baseUrl: String = ApiClient.BASE_URL,
    httpClientEngine: HttpClientEngine? = null,
    httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
    ) : ApiClient(
        baseUrl,
        httpClientEngine,
        httpClientConfig,
    ) {

        /**
        * GET /user/{userId}/watchlist
        * Get the Plex watchlist for a specific user
        * Retrieves a user&#39;s Plex Watchlist in a JSON object. 
         * @param userId  
         * @param page  (optional, default to 1)
         * @return UserUserIdWatchlistGet200Response
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun userUserIdWatchlistGet(userId: java.math.BigDecimal, page: java.math.BigDecimal?): HttpResponse<UserUserIdWatchlistGet200Response> {

            val localVariableAuthNames = listOf<String>("apiKey", "cookieAuth")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()
            page?.apply { localVariableQuery["page"] = listOf("$page") }

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/user/{userId}/watchlist".replace("{" + "userId" + "}", "$userId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * POST /watchlist
        * Add media to watchlist
        * 
         * @param watchlist  
         * @return Watchlist
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun watchlistPost(watchlist: Watchlist): HttpResponse<Watchlist> {

            val localVariableAuthNames = listOf<String>("apiKey", "cookieAuth")

            val localVariableBody = watchlist

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/watchlist",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * DELETE /watchlist/{tmdbId}
        * Delete watchlist item
        * Removes a watchlist item.
         * @param tmdbId tmdbId ID 
         * @return void
        */
        open suspend fun watchlistTmdbIdDelete(tmdbId: kotlin.String): HttpResponse<Unit> {

            val localVariableAuthNames = listOf<String>("apiKey", "cookieAuth")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.DELETE,
            "/watchlist/{tmdbId}".replace("{" + "tmdbId" + "}", "$tmdbId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        }
