/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.apis.BlacklistApi
import com.lowiq.jellyfish.jellyseer.models.Blacklist

class BlacklistApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BlacklistApi
        //val apiInstance = BlacklistApi()

        // to test blacklistPost
        should("test blacklistPost") {
            // uncomment below to test blacklistPost
            //val blacklist : Blacklist =  // Blacklist | 
            //apiInstance.blacklistPost(blacklist)
        }

        // to test blacklistTmdbIdDelete
        should("test blacklistTmdbIdDelete") {
            // uncomment below to test blacklistTmdbIdDelete
            //val tmdbId : kotlin.String = 1 // kotlin.String | tmdbId ID
            //apiInstance.blacklistTmdbIdDelete(tmdbId)
        }

        // to test blacklistTmdbIdGet
        should("test blacklistTmdbIdGet") {
            // uncomment below to test blacklistTmdbIdGet
            //val tmdbId : kotlin.String = 1 // kotlin.String | tmdbId ID
            //apiInstance.blacklistTmdbIdGet(tmdbId)
        }

    }
}
