/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.apis.CollectionApi
import com.lowiq.jellyfish.jellyseer.models.Collection

class CollectionApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CollectionApi
        //val apiInstance = CollectionApi()

        // to test collectionCollectionIdGet
        should("test collectionCollectionIdGet") {
            // uncomment below to test collectionCollectionIdGet
            //val collectionId : java.math.BigDecimal = 537982 // java.math.BigDecimal | 
            //val language : kotlin.String = en // kotlin.String | 
            //val result : Collection = apiInstance.collectionCollectionIdGet(collectionId, language)
            //result shouldBe ("TODO")
        }

    }
}
