/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.apis.IssueApi
import com.lowiq.jellyfish.jellyseer.models.Issue
import com.lowiq.jellyfish.jellyseer.models.IssueComment
import com.lowiq.jellyfish.jellyseer.models.IssueCommentCommentIdPutRequest
import com.lowiq.jellyfish.jellyseer.models.IssueCountGet200Response
import com.lowiq.jellyfish.jellyseer.models.IssueGet200Response
import com.lowiq.jellyfish.jellyseer.models.IssueIssueIdCommentPostRequest
import com.lowiq.jellyfish.jellyseer.models.IssuePostRequest

class IssueApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of IssueApi
        //val apiInstance = IssueApi()

        // to test issueCommentCommentIdDelete
        should("test issueCommentCommentIdDelete") {
            // uncomment below to test issueCommentCommentIdDelete
            //val commentId : kotlin.String = 1 // kotlin.String | Issue Comment ID
            //apiInstance.issueCommentCommentIdDelete(commentId)
        }

        // to test issueCommentCommentIdGet
        should("test issueCommentCommentIdGet") {
            // uncomment below to test issueCommentCommentIdGet
            //val commentId : kotlin.String = 1 // kotlin.String | 
            //val result : IssueComment = apiInstance.issueCommentCommentIdGet(commentId)
            //result shouldBe ("TODO")
        }

        // to test issueCommentCommentIdPut
        should("test issueCommentCommentIdPut") {
            // uncomment below to test issueCommentCommentIdPut
            //val commentId : kotlin.String = 1 // kotlin.String | 
            //val issueCommentCommentIdPutRequest : IssueCommentCommentIdPutRequest =  // IssueCommentCommentIdPutRequest | 
            //val result : IssueComment = apiInstance.issueCommentCommentIdPut(commentId, issueCommentCommentIdPutRequest)
            //result shouldBe ("TODO")
        }

        // to test issueCountGet
        should("test issueCountGet") {
            // uncomment below to test issueCountGet
            //val result : IssueCountGet200Response = apiInstance.issueCountGet()
            //result shouldBe ("TODO")
        }

        // to test issueGet
        should("test issueGet") {
            // uncomment below to test issueGet
            //val take : java.math.BigDecimal = 20 // java.math.BigDecimal | 
            //val skip : java.math.BigDecimal = 0 // java.math.BigDecimal | 
            //val sort : kotlin.String = sort_example // kotlin.String | 
            //val filter : kotlin.String = filter_example // kotlin.String | 
            //val requestedBy : java.math.BigDecimal = 1 // java.math.BigDecimal | 
            //val result : IssueGet200Response = apiInstance.issueGet(take, skip, sort, filter, requestedBy)
            //result shouldBe ("TODO")
        }

        // to test issueIssueIdCommentPost
        should("test issueIssueIdCommentPost") {
            // uncomment below to test issueIssueIdCommentPost
            //val issueId : java.math.BigDecimal = 1 // java.math.BigDecimal | 
            //val issueIssueIdCommentPostRequest : IssueIssueIdCommentPostRequest =  // IssueIssueIdCommentPostRequest | 
            //val result : Issue = apiInstance.issueIssueIdCommentPost(issueId, issueIssueIdCommentPostRequest)
            //result shouldBe ("TODO")
        }

        // to test issueIssueIdDelete
        should("test issueIssueIdDelete") {
            // uncomment below to test issueIssueIdDelete
            //val issueId : kotlin.String = 1 // kotlin.String | Issue ID
            //apiInstance.issueIssueIdDelete(issueId)
        }

        // to test issueIssueIdGet
        should("test issueIssueIdGet") {
            // uncomment below to test issueIssueIdGet
            //val issueId : java.math.BigDecimal = 1 // java.math.BigDecimal | 
            //val result : Issue = apiInstance.issueIssueIdGet(issueId)
            //result shouldBe ("TODO")
        }

        // to test issueIssueIdStatusPost
        should("test issueIssueIdStatusPost") {
            // uncomment below to test issueIssueIdStatusPost
            //val issueId : kotlin.String = 1 // kotlin.String | Issue ID
            //val status : kotlin.String = status_example // kotlin.String | New status
            //val result : Issue = apiInstance.issueIssueIdStatusPost(issueId, status)
            //result shouldBe ("TODO")
        }

        // to test issuePost
        should("test issuePost") {
            // uncomment below to test issuePost
            //val issuePostRequest : IssuePostRequest =  // IssuePostRequest | 
            //val result : Issue = apiInstance.issuePost(issuePostRequest)
            //result shouldBe ("TODO")
        }

    }
}
