/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.apis.MediaApi
import com.lowiq.jellyfish.jellyseer.models.MediaGet200Response
import com.lowiq.jellyfish.jellyseer.models.MediaInfo
import com.lowiq.jellyfish.jellyseer.models.MediaMediaIdStatusPostRequest
import com.lowiq.jellyfish.jellyseer.models.MediaMediaIdWatchDataGet200Response

class MediaApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MediaApi
        //val apiInstance = MediaApi()

        // to test mediaGet
        should("test mediaGet") {
            // uncomment below to test mediaGet
            //val take : java.math.BigDecimal = 20 // java.math.BigDecimal | 
            //val skip : java.math.BigDecimal = 0 // java.math.BigDecimal | 
            //val filter : kotlin.String = filter_example // kotlin.String | 
            //val sort : kotlin.String = sort_example // kotlin.String | 
            //val result : MediaGet200Response = apiInstance.mediaGet(take, skip, filter, sort)
            //result shouldBe ("TODO")
        }

        // to test mediaMediaIdDelete
        should("test mediaMediaIdDelete") {
            // uncomment below to test mediaMediaIdDelete
            //val mediaId : kotlin.String = 1 // kotlin.String | Media ID
            //apiInstance.mediaMediaIdDelete(mediaId)
        }

        // to test mediaMediaIdFileDelete
        should("test mediaMediaIdFileDelete") {
            // uncomment below to test mediaMediaIdFileDelete
            //val mediaId : kotlin.String = 1 // kotlin.String | Media ID
            //val is4k : kotlin.Boolean = false // kotlin.Boolean | Whether to remove from 4K service instance (true) or regular service instance (false)
            //apiInstance.mediaMediaIdFileDelete(mediaId, is4k)
        }

        // to test mediaMediaIdStatusPost
        should("test mediaMediaIdStatusPost") {
            // uncomment below to test mediaMediaIdStatusPost
            //val mediaId : kotlin.String = 1 // kotlin.String | Media ID
            //val status : kotlin.String = available // kotlin.String | New status
            //val mediaMediaIdStatusPostRequest : MediaMediaIdStatusPostRequest =  // MediaMediaIdStatusPostRequest | 
            //val result : MediaInfo = apiInstance.mediaMediaIdStatusPost(mediaId, status, mediaMediaIdStatusPostRequest)
            //result shouldBe ("TODO")
        }

        // to test mediaMediaIdWatchDataGet
        should("test mediaMediaIdWatchDataGet") {
            // uncomment below to test mediaMediaIdWatchDataGet
            //val mediaId : kotlin.String = 1 // kotlin.String | Media ID
            //val result : MediaMediaIdWatchDataGet200Response = apiInstance.mediaMediaIdWatchDataGet(mediaId)
            //result shouldBe ("TODO")
        }

    }
}
