/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.apis.MoviesApi
import com.lowiq.jellyfish.jellyseer.models.DiscoverMoviesGet200Response
import com.lowiq.jellyfish.jellyseer.models.MovieDetails
import com.lowiq.jellyfish.jellyseer.models.MovieMovieIdRatingsGet200Response
import com.lowiq.jellyfish.jellyseer.models.MovieMovieIdRatingscombinedGet200Response

class MoviesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MoviesApi
        //val apiInstance = MoviesApi()

        // to test movieMovieIdGet
        should("test movieMovieIdGet") {
            // uncomment below to test movieMovieIdGet
            //val movieId : java.math.BigDecimal = 337401 // java.math.BigDecimal | 
            //val language : kotlin.String = en // kotlin.String | 
            //val result : MovieDetails = apiInstance.movieMovieIdGet(movieId, language)
            //result shouldBe ("TODO")
        }

        // to test movieMovieIdRatingsGet
        should("test movieMovieIdRatingsGet") {
            // uncomment below to test movieMovieIdRatingsGet
            //val movieId : java.math.BigDecimal = 337401 // java.math.BigDecimal | 
            //val result : MovieMovieIdRatingsGet200Response = apiInstance.movieMovieIdRatingsGet(movieId)
            //result shouldBe ("TODO")
        }

        // to test movieMovieIdRatingscombinedGet
        should("test movieMovieIdRatingscombinedGet") {
            // uncomment below to test movieMovieIdRatingscombinedGet
            //val movieId : java.math.BigDecimal = 337401 // java.math.BigDecimal | 
            //val result : MovieMovieIdRatingscombinedGet200Response = apiInstance.movieMovieIdRatingscombinedGet(movieId)
            //result shouldBe ("TODO")
        }

        // to test movieMovieIdRecommendationsGet
        should("test movieMovieIdRecommendationsGet") {
            // uncomment below to test movieMovieIdRecommendationsGet
            //val movieId : java.math.BigDecimal = 337401 // java.math.BigDecimal | 
            //val page : java.math.BigDecimal = 1 // java.math.BigDecimal | 
            //val language : kotlin.String = en // kotlin.String | 
            //val result : DiscoverMoviesGet200Response = apiInstance.movieMovieIdRecommendationsGet(movieId, page, language)
            //result shouldBe ("TODO")
        }

        // to test movieMovieIdSimilarGet
        should("test movieMovieIdSimilarGet") {
            // uncomment below to test movieMovieIdSimilarGet
            //val movieId : java.math.BigDecimal = 337401 // java.math.BigDecimal | 
            //val page : java.math.BigDecimal = 1 // java.math.BigDecimal | 
            //val language : kotlin.String = en // kotlin.String | 
            //val result : DiscoverMoviesGet200Response = apiInstance.movieMovieIdSimilarGet(movieId, page, language)
            //result shouldBe ("TODO")
        }

    }
}
