/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.apis.OtherApi
import com.lowiq.jellyfish.jellyseer.models.CertificationResponse
import com.lowiq.jellyfish.jellyseer.models.CertificationsMovieGet500Response
import com.lowiq.jellyfish.jellyseer.models.CertificationsTvGet500Response
import com.lowiq.jellyfish.jellyseer.models.Keyword
import com.lowiq.jellyfish.jellyseer.models.KeywordKeywordIdGet500Response
import com.lowiq.jellyfish.jellyseer.models.WatchProviderDetails
import com.lowiq.jellyfish.jellyseer.models.WatchProviderRegion

class OtherApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OtherApi
        //val apiInstance = OtherApi()

        // to test certificationsMovieGet
        should("test certificationsMovieGet") {
            // uncomment below to test certificationsMovieGet
            //val result : CertificationResponse = apiInstance.certificationsMovieGet()
            //result shouldBe ("TODO")
        }

        // to test certificationsTvGet
        should("test certificationsTvGet") {
            // uncomment below to test certificationsTvGet
            //val result : CertificationResponse = apiInstance.certificationsTvGet()
            //result shouldBe ("TODO")
        }

        // to test keywordKeywordIdGet
        should("test keywordKeywordIdGet") {
            // uncomment below to test keywordKeywordIdGet
            //val keywordId : java.math.BigDecimal = 1 // java.math.BigDecimal | 
            //val result : Keyword = apiInstance.keywordKeywordIdGet(keywordId)
            //result shouldBe ("TODO")
        }

        // to test watchprovidersMoviesGet
        should("test watchprovidersMoviesGet") {
            // uncomment below to test watchprovidersMoviesGet
            //val watchRegion : kotlin.String = US // kotlin.String | 
            //val result : kotlin.collections.List<WatchProviderDetails> = apiInstance.watchprovidersMoviesGet(watchRegion)
            //result shouldBe ("TODO")
        }

        // to test watchprovidersRegionsGet
        should("test watchprovidersRegionsGet") {
            // uncomment below to test watchprovidersRegionsGet
            //val result : kotlin.collections.List<WatchProviderRegion> = apiInstance.watchprovidersRegionsGet()
            //result shouldBe ("TODO")
        }

        // to test watchprovidersTvGet
        should("test watchprovidersTvGet") {
            // uncomment below to test watchprovidersTvGet
            //val watchRegion : kotlin.String = US // kotlin.String | 
            //val result : kotlin.collections.List<WatchProviderDetails> = apiInstance.watchprovidersTvGet(watchRegion)
            //result shouldBe ("TODO")
        }

    }
}
