/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.apis.PublicApi
import com.lowiq.jellyfish.jellyseer.models.StatusAppdataGet200Response
import com.lowiq.jellyfish.jellyseer.models.StatusGet200Response

class PublicApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PublicApi
        //val apiInstance = PublicApi()

        // to test statusAppdataGet
        should("test statusAppdataGet") {
            // uncomment below to test statusAppdataGet
            //val result : StatusAppdataGet200Response = apiInstance.statusAppdataGet()
            //result shouldBe ("TODO")
        }

        // to test statusGet
        should("test statusGet") {
            // uncomment below to test statusGet
            //val result : StatusGet200Response = apiInstance.statusGet()
            //result shouldBe ("TODO")
        }

    }
}
