/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.apis.TmdbApi
import com.lowiq.jellyfish.jellyseer.models.GenresMovieGet200ResponseInner
import com.lowiq.jellyfish.jellyseer.models.GenresTvGet200ResponseInner
import com.lowiq.jellyfish.jellyseer.models.LanguagesGet200ResponseInner
import com.lowiq.jellyfish.jellyseer.models.ProductionCompany
import com.lowiq.jellyfish.jellyseer.models.RegionsGet200ResponseInner

class TmdbApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TmdbApi
        //val apiInstance = TmdbApi()

        // to test backdropsGet
        should("test backdropsGet") {
            // uncomment below to test backdropsGet
            //val result : kotlin.collections.List<kotlin.String> = apiInstance.backdropsGet()
            //result shouldBe ("TODO")
        }

        // to test genresMovieGet
        should("test genresMovieGet") {
            // uncomment below to test genresMovieGet
            //val language : kotlin.String = en // kotlin.String | 
            //val result : kotlin.collections.List<GenresMovieGet200ResponseInner> = apiInstance.genresMovieGet(language)
            //result shouldBe ("TODO")
        }

        // to test genresTvGet
        should("test genresTvGet") {
            // uncomment below to test genresTvGet
            //val language : kotlin.String = en // kotlin.String | 
            //val result : kotlin.collections.List<GenresTvGet200ResponseInner> = apiInstance.genresTvGet(language)
            //result shouldBe ("TODO")
        }

        // to test languagesGet
        should("test languagesGet") {
            // uncomment below to test languagesGet
            //val result : kotlin.collections.List<LanguagesGet200ResponseInner> = apiInstance.languagesGet()
            //result shouldBe ("TODO")
        }

        // to test networkNetworkIdGet
        should("test networkNetworkIdGet") {
            // uncomment below to test networkNetworkIdGet
            //val networkId : java.math.BigDecimal = 1 // java.math.BigDecimal | 
            //val result : ProductionCompany = apiInstance.networkNetworkIdGet(networkId)
            //result shouldBe ("TODO")
        }

        // to test regionsGet
        should("test regionsGet") {
            // uncomment below to test regionsGet
            //val result : kotlin.collections.List<RegionsGet200ResponseInner> = apiInstance.regionsGet()
            //result shouldBe ("TODO")
        }

        // to test studioStudioIdGet
        should("test studioStudioIdGet") {
            // uncomment below to test studioStudioIdGet
            //val studioId : java.math.BigDecimal = 2 // java.math.BigDecimal | 
            //val result : ProductionCompany = apiInstance.studioStudioIdGet(studioId)
            //result shouldBe ("TODO")
        }

    }
}
