/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.apis.UsersApi
import com.lowiq.jellyfish.jellyseer.models.AuthLogoutPost200Response
import com.lowiq.jellyfish.jellyseer.models.AuthPlexPostRequest
import com.lowiq.jellyfish.jellyseer.models.AuthResetPasswordGuidPostRequest
import com.lowiq.jellyfish.jellyseer.models.AuthResetPasswordPostRequest
import com.lowiq.jellyfish.jellyseer.models.SettingsJellyfinUsersGet200ResponseInner
import com.lowiq.jellyfish.jellyseer.models.SettingsPlexUsersGet200ResponseInner
import com.lowiq.jellyfish.jellyseer.models.User
import com.lowiq.jellyfish.jellyseer.models.UserGet200Response
import com.lowiq.jellyfish.jellyseer.models.UserImportFromJellyfinPostRequest
import com.lowiq.jellyfish.jellyseer.models.UserImportFromPlexPostRequest
import com.lowiq.jellyfish.jellyseer.models.UserPostRequest
import com.lowiq.jellyfish.jellyseer.models.UserPutRequest
import com.lowiq.jellyfish.jellyseer.models.UserRegisterPushSubscriptionPostRequest
import com.lowiq.jellyfish.jellyseer.models.UserSettings
import com.lowiq.jellyfish.jellyseer.models.UserSettingsNotifications
import com.lowiq.jellyfish.jellyseer.models.UserUserIdPushSubscriptionsGet200Response
import com.lowiq.jellyfish.jellyseer.models.UserUserIdQuotaGet200Response
import com.lowiq.jellyfish.jellyseer.models.UserUserIdRequestsGet200Response
import com.lowiq.jellyfish.jellyseer.models.UserUserIdSettingsLinkedAccountsJellyfinPostRequest
import com.lowiq.jellyfish.jellyseer.models.UserUserIdSettingsPasswordGet200Response
import com.lowiq.jellyfish.jellyseer.models.UserUserIdSettingsPasswordPostRequest
import com.lowiq.jellyfish.jellyseer.models.UserUserIdSettingsPermissionsGet200Response
import com.lowiq.jellyfish.jellyseer.models.UserUserIdSettingsPermissionsPostRequest
import com.lowiq.jellyfish.jellyseer.models.UserUserIdWatchDataGet200Response
import com.lowiq.jellyfish.jellyseer.models.UserUserIdWatchlistGet200Response

class UsersApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UsersApi
        //val apiInstance = UsersApi()

        // to test authMeGet
        should("test authMeGet") {
            // uncomment below to test authMeGet
            //val result : User = apiInstance.authMeGet()
            //result shouldBe ("TODO")
        }

        // to test authResetPasswordGuidPost
        should("test authResetPasswordGuidPost") {
            // uncomment below to test authResetPasswordGuidPost
            //val guid : kotlin.String = 9afef5a7-ec89-4d5f-9397-261e96970b50 // kotlin.String | 
            //val authResetPasswordGuidPostRequest : AuthResetPasswordGuidPostRequest =  // AuthResetPasswordGuidPostRequest | 
            //val result : AuthLogoutPost200Response = apiInstance.authResetPasswordGuidPost(guid, authResetPasswordGuidPostRequest)
            //result shouldBe ("TODO")
        }

        // to test authResetPasswordPost
        should("test authResetPasswordPost") {
            // uncomment below to test authResetPasswordPost
            //val authResetPasswordPostRequest : AuthResetPasswordPostRequest =  // AuthResetPasswordPostRequest | 
            //val result : AuthLogoutPost200Response = apiInstance.authResetPasswordPost(authResetPasswordPostRequest)
            //result shouldBe ("TODO")
        }

        // to test settingsJellyfinUsersGet
        should("test settingsJellyfinUsersGet") {
            // uncomment below to test settingsJellyfinUsersGet
            //val result : kotlin.collections.List<SettingsJellyfinUsersGet200ResponseInner> = apiInstance.settingsJellyfinUsersGet()
            //result shouldBe ("TODO")
        }

        // to test settingsPlexUsersGet
        should("test settingsPlexUsersGet") {
            // uncomment below to test settingsPlexUsersGet
            //val result : kotlin.collections.List<SettingsPlexUsersGet200ResponseInner> = apiInstance.settingsPlexUsersGet()
            //result shouldBe ("TODO")
        }

        // to test userGet
        should("test userGet") {
            // uncomment below to test userGet
            //val take : java.math.BigDecimal = 20 // java.math.BigDecimal | 
            //val skip : java.math.BigDecimal = 0 // java.math.BigDecimal | 
            //val sort : kotlin.String = sort_example // kotlin.String | 
            //val q : kotlin.String = q_example // kotlin.String | 
            //val includeIds : kotlin.String = includeIds_example // kotlin.String | 
            //val result : UserGet200Response = apiInstance.userGet(take, skip, sort, q, includeIds)
            //result shouldBe ("TODO")
        }

        // to test userImportFromJellyfinPost
        should("test userImportFromJellyfinPost") {
            // uncomment below to test userImportFromJellyfinPost
            //val userImportFromJellyfinPostRequest : UserImportFromJellyfinPostRequest =  // UserImportFromJellyfinPostRequest | 
            //val result : kotlin.collections.List<User> = apiInstance.userImportFromJellyfinPost(userImportFromJellyfinPostRequest)
            //result shouldBe ("TODO")
        }

        // to test userImportFromPlexPost
        should("test userImportFromPlexPost") {
            // uncomment below to test userImportFromPlexPost
            //val userImportFromPlexPostRequest : UserImportFromPlexPostRequest =  // UserImportFromPlexPostRequest | 
            //val result : kotlin.collections.List<User> = apiInstance.userImportFromPlexPost(userImportFromPlexPostRequest)
            //result shouldBe ("TODO")
        }

        // to test userPost
        should("test userPost") {
            // uncomment below to test userPost
            //val userPostRequest : UserPostRequest =  // UserPostRequest | 
            //val result : User = apiInstance.userPost(userPostRequest)
            //result shouldBe ("TODO")
        }

        // to test userPut
        should("test userPut") {
            // uncomment below to test userPut
            //val userPutRequest : UserPutRequest =  // UserPutRequest | 
            //val result : kotlin.collections.List<User> = apiInstance.userPut(userPutRequest)
            //result shouldBe ("TODO")
        }

        // to test userRegisterPushSubscriptionPost
        should("test userRegisterPushSubscriptionPost") {
            // uncomment below to test userRegisterPushSubscriptionPost
            //val userRegisterPushSubscriptionPostRequest : UserRegisterPushSubscriptionPostRequest =  // UserRegisterPushSubscriptionPostRequest | 
            //apiInstance.userRegisterPushSubscriptionPost(userRegisterPushSubscriptionPostRequest)
        }

        // to test userUserIdDelete
        should("test userUserIdDelete") {
            // uncomment below to test userUserIdDelete
            //val userId : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val result : User = apiInstance.userUserIdDelete(userId)
            //result shouldBe ("TODO")
        }

        // to test userUserIdGet
        should("test userUserIdGet") {
            // uncomment below to test userUserIdGet
            //val userId : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val result : User = apiInstance.userUserIdGet(userId)
            //result shouldBe ("TODO")
        }

        // to test userUserIdPushSubscriptionEndpointDelete
        should("test userUserIdPushSubscriptionEndpointDelete") {
            // uncomment below to test userUserIdPushSubscriptionEndpointDelete
            //val userId : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val endpoint : kotlin.String = endpoint_example // kotlin.String | 
            //apiInstance.userUserIdPushSubscriptionEndpointDelete(userId, endpoint)
        }

        // to test userUserIdPushSubscriptionEndpointGet
        should("test userUserIdPushSubscriptionEndpointGet") {
            // uncomment below to test userUserIdPushSubscriptionEndpointGet
            //val userId : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val endpoint : kotlin.String = endpoint_example // kotlin.String | 
            //val result : UserUserIdPushSubscriptionsGet200Response = apiInstance.userUserIdPushSubscriptionEndpointGet(userId, endpoint)
            //result shouldBe ("TODO")
        }

        // to test userUserIdPushSubscriptionsGet
        should("test userUserIdPushSubscriptionsGet") {
            // uncomment below to test userUserIdPushSubscriptionsGet
            //val userId : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val result : UserUserIdPushSubscriptionsGet200Response = apiInstance.userUserIdPushSubscriptionsGet(userId)
            //result shouldBe ("TODO")
        }

        // to test userUserIdPut
        should("test userUserIdPut") {
            // uncomment below to test userUserIdPut
            //val userId : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val user : User =  // User | 
            //val result : User = apiInstance.userUserIdPut(userId, user)
            //result shouldBe ("TODO")
        }

        // to test userUserIdQuotaGet
        should("test userUserIdQuotaGet") {
            // uncomment below to test userUserIdQuotaGet
            //val userId : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val result : UserUserIdQuotaGet200Response = apiInstance.userUserIdQuotaGet(userId)
            //result shouldBe ("TODO")
        }

        // to test userUserIdRequestsGet
        should("test userUserIdRequestsGet") {
            // uncomment below to test userUserIdRequestsGet
            //val userId : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val take : java.math.BigDecimal = 20 // java.math.BigDecimal | 
            //val skip : java.math.BigDecimal = 0 // java.math.BigDecimal | 
            //val result : UserUserIdRequestsGet200Response = apiInstance.userUserIdRequestsGet(userId, take, skip)
            //result shouldBe ("TODO")
        }

        // to test userUserIdSettingsLinkedAccountsJellyfinDelete
        should("test userUserIdSettingsLinkedAccountsJellyfinDelete") {
            // uncomment below to test userUserIdSettingsLinkedAccountsJellyfinDelete
            //val userId : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //apiInstance.userUserIdSettingsLinkedAccountsJellyfinDelete(userId)
        }

        // to test userUserIdSettingsLinkedAccountsJellyfinPost
        should("test userUserIdSettingsLinkedAccountsJellyfinPost") {
            // uncomment below to test userUserIdSettingsLinkedAccountsJellyfinPost
            //val userId : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val userUserIdSettingsLinkedAccountsJellyfinPostRequest : UserUserIdSettingsLinkedAccountsJellyfinPostRequest =  // UserUserIdSettingsLinkedAccountsJellyfinPostRequest | 
            //apiInstance.userUserIdSettingsLinkedAccountsJellyfinPost(userId, userUserIdSettingsLinkedAccountsJellyfinPostRequest)
        }

        // to test userUserIdSettingsLinkedAccountsPlexDelete
        should("test userUserIdSettingsLinkedAccountsPlexDelete") {
            // uncomment below to test userUserIdSettingsLinkedAccountsPlexDelete
            //val userId : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //apiInstance.userUserIdSettingsLinkedAccountsPlexDelete(userId)
        }

        // to test userUserIdSettingsLinkedAccountsPlexPost
        should("test userUserIdSettingsLinkedAccountsPlexPost") {
            // uncomment below to test userUserIdSettingsLinkedAccountsPlexPost
            //val userId : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val authPlexPostRequest : AuthPlexPostRequest =  // AuthPlexPostRequest | 
            //apiInstance.userUserIdSettingsLinkedAccountsPlexPost(userId, authPlexPostRequest)
        }

        // to test userUserIdSettingsMainGet
        should("test userUserIdSettingsMainGet") {
            // uncomment below to test userUserIdSettingsMainGet
            //val userId : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val result : UserSettings = apiInstance.userUserIdSettingsMainGet(userId)
            //result shouldBe ("TODO")
        }

        // to test userUserIdSettingsMainPost
        should("test userUserIdSettingsMainPost") {
            // uncomment below to test userUserIdSettingsMainPost
            //val userId : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val userSettings : UserSettings =  // UserSettings | 
            //val result : UserSettings = apiInstance.userUserIdSettingsMainPost(userId, userSettings)
            //result shouldBe ("TODO")
        }

        // to test userUserIdSettingsNotificationsGet
        should("test userUserIdSettingsNotificationsGet") {
            // uncomment below to test userUserIdSettingsNotificationsGet
            //val userId : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val result : UserSettingsNotifications = apiInstance.userUserIdSettingsNotificationsGet(userId)
            //result shouldBe ("TODO")
        }

        // to test userUserIdSettingsNotificationsPost
        should("test userUserIdSettingsNotificationsPost") {
            // uncomment below to test userUserIdSettingsNotificationsPost
            //val userId : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val userSettingsNotifications : UserSettingsNotifications =  // UserSettingsNotifications | 
            //val result : UserSettingsNotifications = apiInstance.userUserIdSettingsNotificationsPost(userId, userSettingsNotifications)
            //result shouldBe ("TODO")
        }

        // to test userUserIdSettingsPasswordGet
        should("test userUserIdSettingsPasswordGet") {
            // uncomment below to test userUserIdSettingsPasswordGet
            //val userId : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val result : UserUserIdSettingsPasswordGet200Response = apiInstance.userUserIdSettingsPasswordGet(userId)
            //result shouldBe ("TODO")
        }

        // to test userUserIdSettingsPasswordPost
        should("test userUserIdSettingsPasswordPost") {
            // uncomment below to test userUserIdSettingsPasswordPost
            //val userId : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val userUserIdSettingsPasswordPostRequest : UserUserIdSettingsPasswordPostRequest =  // UserUserIdSettingsPasswordPostRequest | 
            //apiInstance.userUserIdSettingsPasswordPost(userId, userUserIdSettingsPasswordPostRequest)
        }

        // to test userUserIdSettingsPermissionsGet
        should("test userUserIdSettingsPermissionsGet") {
            // uncomment below to test userUserIdSettingsPermissionsGet
            //val userId : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val result : UserUserIdSettingsPermissionsGet200Response = apiInstance.userUserIdSettingsPermissionsGet(userId)
            //result shouldBe ("TODO")
        }

        // to test userUserIdSettingsPermissionsPost
        should("test userUserIdSettingsPermissionsPost") {
            // uncomment below to test userUserIdSettingsPermissionsPost
            //val userId : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val userUserIdSettingsPermissionsPostRequest : UserUserIdSettingsPermissionsPostRequest =  // UserUserIdSettingsPermissionsPostRequest | 
            //val result : UserUserIdSettingsPermissionsGet200Response = apiInstance.userUserIdSettingsPermissionsPost(userId, userUserIdSettingsPermissionsPostRequest)
            //result shouldBe ("TODO")
        }

        // to test userUserIdWatchDataGet
        should("test userUserIdWatchDataGet") {
            // uncomment below to test userUserIdWatchDataGet
            //val userId : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val result : UserUserIdWatchDataGet200Response = apiInstance.userUserIdWatchDataGet(userId)
            //result shouldBe ("TODO")
        }

        // to test userUserIdWatchlistGet
        should("test userUserIdWatchlistGet") {
            // uncomment below to test userUserIdWatchlistGet
            //val userId : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val page : java.math.BigDecimal = 1 // java.math.BigDecimal | 
            //val result : UserUserIdWatchlistGet200Response = apiInstance.userUserIdWatchlistGet(userId, page)
            //result shouldBe ("TODO")
        }

    }
}
