/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.apis.WatchlistApi
import com.lowiq.jellyfish.jellyseer.models.UserUserIdWatchlistGet200Response
import com.lowiq.jellyfish.jellyseer.models.Watchlist

class WatchlistApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WatchlistApi
        //val apiInstance = WatchlistApi()

        // to test userUserIdWatchlistGet
        should("test userUserIdWatchlistGet") {
            // uncomment below to test userUserIdWatchlistGet
            //val userId : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val page : java.math.BigDecimal = 1 // java.math.BigDecimal | 
            //val result : UserUserIdWatchlistGet200Response = apiInstance.userUserIdWatchlistGet(userId, page)
            //result shouldBe ("TODO")
        }

        // to test watchlistPost
        should("test watchlistPost") {
            // uncomment below to test watchlistPost
            //val watchlist : Watchlist =  // Watchlist | 
            //val result : Watchlist = apiInstance.watchlistPost(watchlist)
            //result shouldBe ("TODO")
        }

        // to test watchlistTmdbIdDelete
        should("test watchlistTmdbIdDelete") {
            // uncomment below to test watchlistTmdbIdDelete
            //val tmdbId : kotlin.String = 1 // kotlin.String | tmdbId ID
            //apiInstance.watchlistTmdbIdDelete(tmdbId)
        }

    }
}
