/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param username 
 * @param password 
 * @param hostname 
 * @param email 
 * @param serverType 
 */
@Serializable

data class AuthJellyfinPostRequest (

    @SerialName(value = "username")
    val username: kotlin.String,

    @SerialName(value = "password")
    val password: kotlin.String,

    @SerialName(value = "hostname")
    val hostname: kotlin.String? = null,

    @SerialName(value = "email")
    val email: kotlin.String? = null,

    @Contextual @SerialName(value = "serverType")
    val serverType: java.math.BigDecimal? = null

) {


}

