/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import com.lowiq.jellyfish.jellyseer.models.User

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param user 
 * @param createdAt 
 * @param id 
 * @param mediaType 
 * @param title 
 * @param tmdbId 
 */
@Serializable

data class BlacklistGet200ResponseResultsInner (

    @SerialName(value = "user")
    val user: User? = null,

    @SerialName(value = "createdAt")
    val createdAt: kotlin.String? = null,

    @Contextual @SerialName(value = "id")
    val id: java.math.BigDecimal? = null,

    @SerialName(value = "mediaType")
    val mediaType: kotlin.String? = null,

    @SerialName(value = "title")
    val title: kotlin.String? = null,

    @Contextual @SerialName(value = "tmdbId")
    val tmdbId: java.math.BigDecimal? = null

) {


}

