/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import com.lowiq.jellyfish.jellyseer.models.MediaInfo

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param tmdbId 
 * @param title 
 * @param media 
 * @param userId 
 */
@Serializable

data class Blacklist (

    @Contextual @SerialName(value = "tmdbId")
    val tmdbId: java.math.BigDecimal? = null,

    @SerialName(value = "title")
    val title: kotlin.String? = null,

    @SerialName(value = "media")
    val media: MediaInfo? = null,

    @Contextual @SerialName(value = "userId")
    val userId: java.math.BigDecimal? = null

) {


}

