/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param certification 
 * @param meaning 
 * @param order 
 */
@Serializable

data class Certification (

    @SerialName(value = "certification")
    val certification: kotlin.String,

    @SerialName(value = "meaning")
    val meaning: kotlin.String? = null,

    @Contextual @SerialName(value = "order")
    val order: java.math.BigDecimal? = null

) {


}

