/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param creditId 
 * @param gender 
 * @param name 
 * @param job 
 * @param department 
 * @param profilePath 
 */
@Serializable

data class Crew (

    @Contextual @SerialName(value = "id")
    val id: java.math.BigDecimal? = null,

    @SerialName(value = "creditId")
    val creditId: kotlin.String? = null,

    @Contextual @SerialName(value = "gender")
    val gender: java.math.BigDecimal? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "job")
    val job: kotlin.String? = null,

    @SerialName(value = "department")
    val department: kotlin.String? = null,

    @SerialName(value = "profilePath")
    val profilePath: kotlin.String? = null

) {


}

