/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import com.lowiq.jellyfish.jellyseer.models.MovieResult
import com.lowiq.jellyfish.jellyseer.models.SpokenLanguage

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param page 
 * @param totalPages 
 * @param totalResults 
 * @param language 
 * @param results 
 */
@Serializable

data class DiscoverMoviesLanguageLanguageGet200Response (

    @Contextual @SerialName(value = "page")
    val page: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "totalPages")
    val totalPages: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "totalResults")
    val totalResults: java.math.BigDecimal? = null,

    @SerialName(value = "language")
    val language: SpokenLanguage? = null,

    @SerialName(value = "results")
    val results: kotlin.collections.List<MovieResult>? = null

) {


}

