/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param type 
 * @param title 
 * @param enabled 
 * @param `data` 
 * @param id 
 * @param isBuiltIn 
 */
@Serializable

data class DiscoverSlider (

    @Contextual @SerialName(value = "type")
    val type: java.math.BigDecimal,

    @SerialName(value = "title")
    val title: kotlin.String?,

    @SerialName(value = "enabled")
    val enabled: kotlin.Boolean,

    @SerialName(value = "data")
    val `data`: kotlin.String?,

    @Contextual @SerialName(value = "id")
    val id: java.math.BigDecimal? = null,

    @SerialName(value = "isBuiltIn")
    val isBuiltIn: kotlin.Boolean? = null

) {


}

