/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import com.lowiq.jellyfish.jellyseer.models.IssueComment
import com.lowiq.jellyfish.jellyseer.models.MediaInfo
import com.lowiq.jellyfish.jellyseer.models.User

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param issueType 
 * @param media 
 * @param createdBy 
 * @param modifiedBy 
 * @param comments 
 */
@Serializable

data class Issue (

    @Contextual @SerialName(value = "id")
    val id: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "issueType")
    val issueType: java.math.BigDecimal? = null,

    @SerialName(value = "media")
    val media: MediaInfo? = null,

    @SerialName(value = "createdBy")
    val createdBy: User? = null,

    @SerialName(value = "modifiedBy")
    val modifiedBy: User? = null,

    @SerialName(value = "comments")
    val comments: kotlin.collections.List<IssueComment>? = null

) {


}

