/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import com.lowiq.jellyfish.jellyseer.models.JellyfinLibrary

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param name 
 * @param hostname 
 * @param externalHostname 
 * @param jellyfinForgotPasswordUrl 
 * @param adminUser 
 * @param adminPass 
 * @param libraries 
 * @param serverID 
 */
@Serializable

data class JellyfinSettings (

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "hostname")
    val hostname: kotlin.String? = null,

    @SerialName(value = "externalHostname")
    val externalHostname: kotlin.String? = null,

    @SerialName(value = "jellyfinForgotPasswordUrl")
    val jellyfinForgotPasswordUrl: kotlin.String? = null,

    @SerialName(value = "adminUser")
    val adminUser: kotlin.String? = null,

    @SerialName(value = "adminPass")
    val adminPass: kotlin.String? = null,

    @SerialName(value = "libraries")
    val libraries: kotlin.collections.List<JellyfinLibrary>? = null,

    @SerialName(value = "serverID")
    val serverID: kotlin.String? = null

) {


}

