/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param iso6391 
 * @param englishName 
 * @param name 
 */
@Serializable

data class LanguagesGet200ResponseInner (

    @SerialName(value = "iso_639_1")
    val iso6391: kotlin.String? = null,

    @SerialName(value = "english_name")
    val englishName: kotlin.String? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null

) {


}

