/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import com.lowiq.jellyfish.jellyseer.models.MediaInfo
import com.lowiq.jellyfish.jellyseer.models.MediaRequestModifiedBy
import com.lowiq.jellyfish.jellyseer.models.User

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param status Status of the request. 1 = PENDING APPROVAL, 2 = APPROVED, 3 = DECLINED
 * @param media 
 * @param createdAt 
 * @param updatedAt 
 * @param requestedBy 
 * @param modifiedBy 
 * @param is4k 
 * @param serverId 
 * @param profileId 
 * @param rootFolder 
 */
@Serializable

data class MediaRequest (

    @Contextual @SerialName(value = "id")
    val id: java.math.BigDecimal,

    /* Status of the request. 1 = PENDING APPROVAL, 2 = APPROVED, 3 = DECLINED */
    @Contextual @SerialName(value = "status")
    val status: java.math.BigDecimal,

    @SerialName(value = "media")
    val media: MediaInfo? = null,

    @SerialName(value = "createdAt")
    val createdAt: kotlin.String? = null,

    @SerialName(value = "updatedAt")
    val updatedAt: kotlin.String? = null,

    @SerialName(value = "requestedBy")
    val requestedBy: User? = null,

    @SerialName(value = "modifiedBy")
    val modifiedBy: MediaRequestModifiedBy? = null,

    @SerialName(value = "is4k")
    val is4k: kotlin.Boolean? = null,

    @Contextual @SerialName(value = "serverId")
    val serverId: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "profileId")
    val profileId: java.math.BigDecimal? = null,

    @SerialName(value = "rootFolder")
    val rootFolder: kotlin.String? = null

) {


}

