/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param name 
 * @param posterPath 
 * @param backdropPath 
 */
@Serializable

data class MovieDetailsCollection (

    @Contextual @SerialName(value = "id")
    val id: java.math.BigDecimal? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "posterPath")
    val posterPath: kotlin.String? = null,

    @SerialName(value = "backdropPath")
    val backdropPath: kotlin.String? = null

) {


}

