/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import com.lowiq.jellyfish.jellyseer.models.MovieDetailsReleasesResultsInnerReleaseDatesInner

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param iso31661 
 * @param rating 
 * @param releaseDates 
 */
@Serializable

data class MovieDetailsReleasesResultsInner (

    @SerialName(value = "iso_3166_1")
    val iso31661: kotlin.String? = null,

    @SerialName(value = "rating")
    val rating: kotlin.String? = null,

    @SerialName(value = "release_dates")
    val releaseDates: kotlin.collections.List<MovieDetailsReleasesResultsInnerReleaseDatesInner>? = null

) {


}

