/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param title 
 * @param year 
 * @param url 
 * @param criticsScore 
 * @param criticsRating 
 * @param audienceScore 
 * @param audienceRating 
 */
@Serializable

data class MovieMovieIdRatingsGet200Response (

    @SerialName(value = "title")
    val title: kotlin.String? = null,

    @Contextual @SerialName(value = "year")
    val year: java.math.BigDecimal? = null,

    @SerialName(value = "url")
    val url: kotlin.String? = null,

    @Contextual @SerialName(value = "criticsScore")
    val criticsScore: java.math.BigDecimal? = null,

    @SerialName(value = "criticsRating")
    val criticsRating: MovieMovieIdRatingsGet200Response.CriticsRating? = null,

    @Contextual @SerialName(value = "audienceScore")
    val audienceScore: java.math.BigDecimal? = null,

    @SerialName(value = "audienceRating")
    val audienceRating: MovieMovieIdRatingsGet200Response.AudienceRating? = null

) {

    /**
     * 
     *
     * Values: Rotten,Fresh,Certified_Fresh
     */
    @Serializable
    enum class CriticsRating(val value: kotlin.String) {
        @SerialName(value = "Rotten") Rotten("Rotten"),
        @SerialName(value = "Fresh") Fresh("Fresh"),
        @SerialName(value = "Certified Fresh") Certified_Fresh("Certified Fresh");
    }
    /**
     * 
     *
     * Values: Spilled,Upright
     */
    @Serializable
    enum class AudienceRating(val value: kotlin.String) {
        @SerialName(value = "Spilled") Spilled("Spilled"),
        @SerialName(value = "Upright") Upright("Upright");
    }

}

