/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param iso31661 
 * @param name 
 */
@Serializable

data class MovieDetailsProductionCountriesInner (

    @SerialName(value = "iso_3166_1")
    val iso31661: kotlin.String? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null

) {


}

