/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param emailFrom 
 * @param senderName 
 * @param smtpHost 
 * @param smtpPort 
 * @param secure 
 * @param ignoreTls 
 * @param requireTls 
 * @param authUser 
 * @param authPass 
 * @param allowSelfSigned 
 */
@Serializable

data class NotificationEmailSettingsOptions (

    @SerialName(value = "emailFrom")
    val emailFrom: kotlin.String? = null,

    @SerialName(value = "senderName")
    val senderName: kotlin.String? = null,

    @SerialName(value = "smtpHost")
    val smtpHost: kotlin.String? = null,

    @Contextual @SerialName(value = "smtpPort")
    val smtpPort: java.math.BigDecimal? = null,

    @SerialName(value = "secure")
    val secure: kotlin.Boolean? = null,

    @SerialName(value = "ignoreTls")
    val ignoreTls: kotlin.Boolean? = null,

    @SerialName(value = "requireTls")
    val requireTls: kotlin.Boolean? = null,

    @SerialName(value = "authUser")
    val authUser: kotlin.String? = null,

    @SerialName(value = "authPass")
    val authPass: kotlin.String? = null,

    @SerialName(value = "allowSelfSigned")
    val allowSelfSigned: kotlin.Boolean? = null

) {


}

