/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param discord 
 * @param email 
 * @param pushbullet 
 * @param pushover 
 * @param slack 
 * @param telegram 
 * @param webhook 
 * @param webpush 
 */
@Serializable

data class NotificationAgentTypes (

    @Contextual @SerialName(value = "discord")
    val discord: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "email")
    val email: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "pushbullet")
    val pushbullet: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "pushover")
    val pushover: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "slack")
    val slack: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "telegram")
    val telegram: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "webhook")
    val webhook: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "webpush")
    val webpush: java.math.BigDecimal? = null

) {


}

