/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param url 
 * @param topic 
 * @param authMethodUsernamePassword 
 * @param username 
 * @param password 
 * @param authMethodToken 
 * @param token 
 */
@Serializable

data class NtfySettingsOptions (

    @SerialName(value = "url")
    val url: kotlin.String? = null,

    @SerialName(value = "topic")
    val topic: kotlin.String? = null,

    @SerialName(value = "authMethodUsernamePassword")
    val authMethodUsernamePassword: kotlin.Boolean? = null,

    @SerialName(value = "username")
    val username: kotlin.String? = null,

    @SerialName(value = "password")
    val password: kotlin.String? = null,

    @SerialName(value = "authMethodToken")
    val authMethodToken: kotlin.Boolean? = null,

    @SerialName(value = "token")
    val token: kotlin.String? = null

) {


}

