/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import com.lowiq.jellyfish.jellyseer.models.CreditCast
import com.lowiq.jellyfish.jellyseer.models.CreditCrew

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param cast 
 * @param crew 
 * @param id 
 */
@Serializable

data class PersonPersonIdCombinedCreditsGet200Response (

    @SerialName(value = "cast")
    val cast: kotlin.collections.List<CreditCast>? = null,

    @SerialName(value = "crew")
    val crew: kotlin.collections.List<CreditCrew>? = null,

    @Contextual @SerialName(value = "id")
    val id: java.math.BigDecimal? = null

) {


}

