/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param name 
 * @param deathday 
 * @param knownForDepartment 
 * @param alsoKnownAs 
 * @param gender 
 * @param biography 
 * @param popularity 
 * @param placeOfBirth 
 * @param profilePath 
 * @param adult 
 * @param imdbId 
 * @param homepage 
 */
@Serializable

data class PersonDetails (

    @Contextual @SerialName(value = "id")
    val id: java.math.BigDecimal? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "deathday")
    val deathday: kotlin.String? = null,

    @SerialName(value = "knownForDepartment")
    val knownForDepartment: kotlin.String? = null,

    @SerialName(value = "alsoKnownAs")
    val alsoKnownAs: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "gender")
    val gender: kotlin.String? = null,

    @SerialName(value = "biography")
    val biography: kotlin.String? = null,

    @SerialName(value = "popularity")
    val popularity: kotlin.String? = null,

    @SerialName(value = "placeOfBirth")
    val placeOfBirth: kotlin.String? = null,

    @SerialName(value = "profilePath")
    val profilePath: kotlin.String? = null,

    @SerialName(value = "adult")
    val adult: kotlin.Boolean? = null,

    @SerialName(value = "imdbId")
    val imdbId: kotlin.String? = null,

    @SerialName(value = "homepage")
    val homepage: kotlin.String? = null

) {


}

