/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import com.lowiq.jellyfish.jellyseer.models.PlexLibrary

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param name 
 * @param machineId 
 * @param ip 
 * @param port 
 * @param useSsl 
 * @param libraries 
 * @param webAppUrl 
 */
@Serializable

data class PlexSettings (

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "machineId")
    val machineId: kotlin.String,

    @SerialName(value = "ip")
    val ip: kotlin.String,

    @Contextual @SerialName(value = "port")
    val port: java.math.BigDecimal,

    @SerialName(value = "useSsl")
    val useSsl: kotlin.Boolean? = null,

    @SerialName(value = "libraries")
    val libraries: kotlin.collections.List<PlexLibrary>? = null,

    @SerialName(value = "webAppUrl")
    val webAppUrl: kotlin.String? = null

) {


}

