/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param name 
 * @param hostname 
 * @param port 
 * @param apiKey 
 * @param useSsl 
 * @param activeProfileId 
 * @param activeProfileName 
 * @param activeDirectory 
 * @param is4k 
 * @param minimumAvailability 
 * @param isDefault 
 * @param id 
 * @param baseUrl 
 * @param externalUrl 
 * @param syncEnabled 
 * @param preventSearch 
 */
@Serializable

data class RadarrSettings (

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "hostname")
    val hostname: kotlin.String,

    @Contextual @SerialName(value = "port")
    val port: java.math.BigDecimal,

    @SerialName(value = "apiKey")
    val apiKey: kotlin.String,

    @SerialName(value = "useSsl")
    val useSsl: kotlin.Boolean,

    @Contextual @SerialName(value = "activeProfileId")
    val activeProfileId: java.math.BigDecimal,

    @SerialName(value = "activeProfileName")
    val activeProfileName: kotlin.String,

    @SerialName(value = "activeDirectory")
    val activeDirectory: kotlin.String,

    @SerialName(value = "is4k")
    val is4k: kotlin.Boolean,

    @SerialName(value = "minimumAvailability")
    val minimumAvailability: kotlin.String,

    @SerialName(value = "isDefault")
    val isDefault: kotlin.Boolean,

    @Contextual @SerialName(value = "id")
    val id: java.math.BigDecimal? = null,

    @SerialName(value = "baseUrl")
    val baseUrl: kotlin.String? = null,

    @SerialName(value = "externalUrl")
    val externalUrl: kotlin.String? = null,

    @SerialName(value = "syncEnabled")
    val syncEnabled: kotlin.Boolean? = null,

    @SerialName(value = "preventSearch")
    val preventSearch: kotlin.Boolean? = null

) {


}

