/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import com.lowiq.jellyfish.jellyseer.models.RequestPostRequestSeasons

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param mediaType 
 * @param mediaId 
 * @param tvdbId 
 * @param seasons 
 * @param is4k 
 * @param serverId 
 * @param profileId 
 * @param rootFolder 
 * @param languageProfileId 
 * @param userId 
 */
@Serializable

data class RequestPostRequest (

    @SerialName(value = "mediaType")
    val mediaType: RequestPostRequest.MediaType,

    @Contextual @SerialName(value = "mediaId")
    val mediaId: java.math.BigDecimal,

    @Contextual @SerialName(value = "tvdbId")
    val tvdbId: java.math.BigDecimal? = null,

    @SerialName(value = "seasons")
    val seasons: RequestPostRequestSeasons? = null,

    @SerialName(value = "is4k")
    val is4k: kotlin.Boolean? = null,

    @Contextual @SerialName(value = "serverId")
    val serverId: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "profileId")
    val profileId: java.math.BigDecimal? = null,

    @SerialName(value = "rootFolder")
    val rootFolder: kotlin.String? = null,

    @Contextual @SerialName(value = "languageProfileId")
    val languageProfileId: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "userId")
    val userId: java.math.BigDecimal? = null

) {

    /**
     * 
     *
     * Values: movie,tv
     */
    @Serializable
    enum class MediaType(val value: kotlin.String) {
        @SerialName(value = "movie") movie("movie"),
        @SerialName(value = "tv") tv("tv");
    }

}

