/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import com.lowiq.jellyfish.jellyseer.models.Episode

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param airDate 
 * @param episodeCount 
 * @param name 
 * @param overview 
 * @param posterPath 
 * @param seasonNumber 
 * @param episodes 
 */
@Serializable

data class Season (

    @Contextual @SerialName(value = "id")
    val id: java.math.BigDecimal? = null,

    @SerialName(value = "airDate")
    val airDate: kotlin.String? = null,

    @Contextual @SerialName(value = "episodeCount")
    val episodeCount: java.math.BigDecimal? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "overview")
    val overview: kotlin.String? = null,

    @SerialName(value = "posterPath")
    val posterPath: kotlin.String? = null,

    @Contextual @SerialName(value = "seasonNumber")
    val seasonNumber: java.math.BigDecimal? = null,

    @SerialName(value = "episodes")
    val episodes: kotlin.collections.List<Episode>? = null

) {


}

