/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import com.lowiq.jellyfish.jellyseer.models.RadarrSettings
import com.lowiq.jellyfish.jellyseer.models.ServiceProfile

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param server 
 * @param profiles 
 */
@Serializable

data class ServiceRadarrRadarrIdGet200Response (

    @SerialName(value = "server")
    val server: RadarrSettings? = null,

    @SerialName(value = "profiles")
    val profiles: ServiceProfile? = null

) {


}

