/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param tmdb 
 * @param tvdb 
 */
@Serializable

data class SettingsMetadatasTestPostRequest (

    @SerialName(value = "tmdb")
    val tmdb: kotlin.Boolean? = null,

    @SerialName(value = "tvdb")
    val tvdb: kotlin.Boolean? = null

) {


}

