/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param label 
 * @param level 
 * @param message 
 * @param timestamp 
 */
@Serializable

data class SettingsLogsGet200ResponseInner (

    @SerialName(value = "label")
    val label: kotlin.String? = null,

    @SerialName(value = "level")
    val level: kotlin.String? = null,

    @SerialName(value = "message")
    val message: kotlin.String? = null,

    @SerialName(value = "timestamp")
    val timestamp: kotlin.String? = null

) {


}

