/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import com.lowiq.jellyfish.jellyseer.models.SettingsCacheGet200ResponseApiCachesInner
import com.lowiq.jellyfish.jellyseer.models.SettingsCacheGet200ResponseDnsCache
import com.lowiq.jellyfish.jellyseer.models.SettingsCacheGet200ResponseImageCache

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param imageCache 
 * @param dnsCache 
 * @param apiCaches 
 */
@Serializable

data class SettingsCacheGet200Response (

    @SerialName(value = "imageCache")
    val imageCache: SettingsCacheGet200ResponseImageCache? = null,

    @SerialName(value = "dnsCache")
    val dnsCache: SettingsCacheGet200ResponseDnsCache? = null,

    @SerialName(value = "apiCaches")
    val apiCaches: kotlin.collections.List<SettingsCacheGet200ResponseApiCachesInner>? = null

) {


}

