/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param hits 
 * @param misses 
 * @param propertyKeys 
 * @param ksize 
 * @param vsize 
 */
@Serializable

data class SettingsCacheGet200ResponseApiCachesInnerStats (

    @Contextual @SerialName(value = "hits")
    val hits: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "misses")
    val misses: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "keys")
    val propertyKeys: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "ksize")
    val ksize: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "vsize")
    val vsize: java.math.BigDecimal? = null

) {


}

