/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import com.lowiq.jellyfish.jellyseer.models.SettingsCacheGet200ResponseDnsCacheEntriesValue
import com.lowiq.jellyfish.jellyseer.models.SettingsCacheGet200ResponseDnsCacheStats

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param stats 
 * @param propertyEntries 
 */
@Serializable

data class SettingsCacheGet200ResponseDnsCache (

    @SerialName(value = "stats")
    val stats: SettingsCacheGet200ResponseDnsCacheStats? = null,

    @Contextual @SerialName(value = "entries")
    val propertyEntries: kotlin.collections.Map<kotlin.String, SettingsCacheGet200ResponseDnsCacheEntriesValue>? = null

) {


}

