/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import com.lowiq.jellyfish.jellyseer.models.SettingsCacheGet200ResponseDnsCacheEntriesValueAddresses

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param addresses 
 * @param activeAddress 
 * @param family 
 * @param age 
 * @param ttl 
 * @param networkErrors 
 * @param hits 
 * @param misses 
 */
@Serializable

data class SettingsCacheGet200ResponseDnsCacheEntriesValue (

    @SerialName(value = "addresses")
    val addresses: SettingsCacheGet200ResponseDnsCacheEntriesValueAddresses? = null,

    @SerialName(value = "activeAddress")
    val activeAddress: kotlin.String? = null,

    @Contextual @SerialName(value = "family")
    val family: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "age")
    val age: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "ttl")
    val ttl: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "networkErrors")
    val networkErrors: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "hits")
    val hits: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "misses")
    val misses: java.math.BigDecimal? = null

) {


}

