/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param seasonNumber 
 * @param monitored 
 */
@Serializable

data class SonarrSeriesSeasonsInner (

    @Contextual @SerialName(value = "seasonNumber")
    val seasonNumber: java.math.BigDecimal? = null,

    @SerialName(value = "monitored")
    val monitored: kotlin.Boolean? = null

) {


}

