/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import com.lowiq.jellyfish.jellyseer.models.MediaInfo

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param mediaType 
 * @param popularity 
 * @param posterPath 
 * @param backdropPath 
 * @param voteCount 
 * @param voteAverage 
 * @param genreIds 
 * @param overview 
 * @param originalLanguage 
 * @param name 
 * @param originalName 
 * @param originCountry 
 * @param firstAirDate 
 * @param mediaInfo 
 */
@Serializable

data class TvResult (

    @Contextual @SerialName(value = "id")
    val id: java.math.BigDecimal? = null,

    @SerialName(value = "mediaType")
    val mediaType: kotlin.String? = null,

    @Contextual @SerialName(value = "popularity")
    val popularity: java.math.BigDecimal? = null,

    @SerialName(value = "posterPath")
    val posterPath: kotlin.String? = null,

    @SerialName(value = "backdropPath")
    val backdropPath: kotlin.String? = null,

    @Contextual @SerialName(value = "voteCount")
    val voteCount: java.math.BigDecimal? = null,

    @Contextual @SerialName(value = "voteAverage")
    val voteAverage: java.math.BigDecimal? = null,

    @SerialName(value = "genreIds")
    val genreIds: kotlin.collections.List<@Contextual java.math.BigDecimal>? = null,

    @SerialName(value = "overview")
    val overview: kotlin.String? = null,

    @SerialName(value = "originalLanguage")
    val originalLanguage: kotlin.String? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "originalName")
    val originalName: kotlin.String? = null,

    @SerialName(value = "originCountry")
    val originCountry: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "firstAirDate")
    val firstAirDate: kotlin.String? = null,

    @SerialName(value = "mediaInfo")
    val mediaInfo: MediaInfo? = null

) {


}

