/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param title 
 * @param year 
 * @param url 
 * @param criticsScore 
 * @param criticsRating 
 */
@Serializable

data class TvTvIdRatingsGet200Response (

    @SerialName(value = "title")
    val title: kotlin.String? = null,

    @Contextual @SerialName(value = "year")
    val year: java.math.BigDecimal? = null,

    @SerialName(value = "url")
    val url: kotlin.String? = null,

    @Contextual @SerialName(value = "criticsScore")
    val criticsScore: java.math.BigDecimal? = null,

    @SerialName(value = "criticsRating")
    val criticsRating: TvTvIdRatingsGet200Response.CriticsRating? = null

) {

    /**
     * 
     *
     * Values: Rotten,Fresh
     */
    @Serializable
    enum class CriticsRating(val value: kotlin.String) {
        @SerialName(value = "Rotten") Rotten("Rotten"),
        @SerialName(value = "Fresh") Fresh("Fresh");
    }

}

