/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param tmdbId 
 * @param ratingKey 
 * @param type 
 * @param title 
 */
@Serializable

data class UserUserIdWatchlistGet200ResponseResultsInner (

    @Contextual @SerialName(value = "tmdbId")
    val tmdbId: java.math.BigDecimal? = null,

    @SerialName(value = "ratingKey")
    val ratingKey: kotlin.String? = null,

    @SerialName(value = "type")
    val type: kotlin.String? = null,

    @SerialName(value = "title")
    val title: kotlin.String? = null

) {


}

