/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import com.lowiq.jellyfish.jellyseer.models.NotificationAgentTypes

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param notificationTypes 
 * @param emailEnabled 
 * @param pgpKey 
 * @param discordEnabled 
 * @param discordEnabledTypes 
 * @param discordId 
 * @param pushbulletAccessToken 
 * @param pushoverApplicationToken 
 * @param pushoverUserKey 
 * @param pushoverSound 
 * @param telegramEnabled 
 * @param telegramBotUsername 
 * @param telegramChatId 
 * @param telegramMessageThreadId 
 * @param telegramSendSilently 
 */
@Serializable

data class UserSettingsNotifications (

    @SerialName(value = "notificationTypes")
    val notificationTypes: NotificationAgentTypes? = null,

    @SerialName(value = "emailEnabled")
    val emailEnabled: kotlin.Boolean? = null,

    @SerialName(value = "pgpKey")
    val pgpKey: kotlin.String? = null,

    @SerialName(value = "discordEnabled")
    val discordEnabled: kotlin.Boolean? = null,

    @Contextual @SerialName(value = "discordEnabledTypes")
    val discordEnabledTypes: java.math.BigDecimal? = null,

    @SerialName(value = "discordId")
    val discordId: kotlin.String? = null,

    @SerialName(value = "pushbulletAccessToken")
    val pushbulletAccessToken: kotlin.String? = null,

    @SerialName(value = "pushoverApplicationToken")
    val pushoverApplicationToken: kotlin.String? = null,

    @SerialName(value = "pushoverUserKey")
    val pushoverUserKey: kotlin.String? = null,

    @SerialName(value = "pushoverSound")
    val pushoverSound: kotlin.String? = null,

    @SerialName(value = "telegramEnabled")
    val telegramEnabled: kotlin.Boolean? = null,

    @SerialName(value = "telegramBotUsername")
    val telegramBotUsername: kotlin.String? = null,

    @SerialName(value = "telegramChatId")
    val telegramChatId: kotlin.String? = null,

    @SerialName(value = "telegramMessageThreadId")
    val telegramMessageThreadId: kotlin.String? = null,

    @SerialName(value = "telegramSendSilently")
    val telegramSendSilently: kotlin.Boolean? = null

) {


}

