/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import com.lowiq.jellyfish.jellyseer.models.MediaInfo

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param recentlyWatched 
 * @param playCount 
 */
@Serializable

data class UserUserIdWatchDataGet200Response (

    @SerialName(value = "recentlyWatched")
    val recentlyWatched: kotlin.collections.List<MediaInfo>? = null,

    @Contextual @SerialName(value = "playCount")
    val playCount: java.math.BigDecimal? = null

) {


}

