/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param webhookUrl 
 * @param authHeader 
 * @param jsonPayload 
 * @param supportVariables 
 */
@Serializable

data class WebhookSettingsOptions (

    @SerialName(value = "webhookUrl")
    val webhookUrl: kotlin.String? = null,

    @SerialName(value = "authHeader")
    val authHeader: kotlin.String? = null,

    @SerialName(value = "jsonPayload")
    val jsonPayload: kotlin.String? = null,

    @SerialName(value = "supportVariables")
    val supportVariables: kotlin.Boolean? = null

) {


}

