/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.Blacklist
import com.lowiq.jellyfish.jellyseer.models.MediaInfo

class BlacklistTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Blacklist
        //val modelInstance = Blacklist()

        // to test the property `tmdbId`
        should("test tmdbId") {
            // uncomment below to test the property
            //modelInstance.tmdbId shouldBe ("TODO")
        }

        // to test the property `title`
        should("test title") {
            // uncomment below to test the property
            //modelInstance.title shouldBe ("TODO")
        }

        // to test the property `media`
        should("test media") {
            // uncomment below to test the property
            //modelInstance.media shouldBe ("TODO")
        }

        // to test the property `userId`
        should("test userId") {
            // uncomment below to test the property
            //modelInstance.userId shouldBe ("TODO")
        }

    }
}
