/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.BlacklistGet200Response
import com.lowiq.jellyfish.jellyseer.models.BlacklistGet200ResponseResultsInner
import com.lowiq.jellyfish.jellyseer.models.PageInfo

class BlacklistGet200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BlacklistGet200Response
        //val modelInstance = BlacklistGet200Response()

        // to test the property `pageInfo`
        should("test pageInfo") {
            // uncomment below to test the property
            //modelInstance.pageInfo shouldBe ("TODO")
        }

        // to test the property `results`
        should("test results") {
            // uncomment below to test the property
            //modelInstance.results shouldBe ("TODO")
        }

    }
}
