/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.CertificationResponse
import com.lowiq.jellyfish.jellyseer.models.Certification

class CertificationResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CertificationResponse
        //val modelInstance = CertificationResponse()

        // to test the property `certifications`
        should("test certifications") {
            // uncomment below to test the property
            //modelInstance.certifications shouldBe ("TODO")
        }

    }
}
