/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.CertificationsTvGet500Response

class CertificationsTvGet500ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CertificationsTvGet500Response
        //val modelInstance = CertificationsTvGet500Response()

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `message`
        should("test message") {
            // uncomment below to test the property
            //modelInstance.message shouldBe ("TODO")
        }

    }
}
