/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.Crew

class CrewTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Crew
        //val modelInstance = Crew()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `creditId`
        should("test creditId") {
            // uncomment below to test the property
            //modelInstance.creditId shouldBe ("TODO")
        }

        // to test the property `gender`
        should("test gender") {
            // uncomment below to test the property
            //modelInstance.gender shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `job`
        should("test job") {
            // uncomment below to test the property
            //modelInstance.job shouldBe ("TODO")
        }

        // to test the property `department`
        should("test department") {
            // uncomment below to test the property
            //modelInstance.department shouldBe ("TODO")
        }

        // to test the property `profilePath`
        should("test profilePath") {
            // uncomment below to test the property
            //modelInstance.profilePath shouldBe ("TODO")
        }

    }
}
