/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.Issue
import com.lowiq.jellyfish.jellyseer.models.IssueComment
import com.lowiq.jellyfish.jellyseer.models.MediaInfo
import com.lowiq.jellyfish.jellyseer.models.User

class IssueTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Issue
        //val modelInstance = Issue()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `issueType`
        should("test issueType") {
            // uncomment below to test the property
            //modelInstance.issueType shouldBe ("TODO")
        }

        // to test the property `media`
        should("test media") {
            // uncomment below to test the property
            //modelInstance.media shouldBe ("TODO")
        }

        // to test the property `createdBy`
        should("test createdBy") {
            // uncomment below to test the property
            //modelInstance.createdBy shouldBe ("TODO")
        }

        // to test the property `modifiedBy`
        should("test modifiedBy") {
            // uncomment below to test the property
            //modelInstance.modifiedBy shouldBe ("TODO")
        }

        // to test the property `comments`
        should("test comments") {
            // uncomment below to test the property
            //modelInstance.comments shouldBe ("TODO")
        }

    }
}
