/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.IssueCountGet200Response

class IssueCountGet200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of IssueCountGet200Response
        //val modelInstance = IssueCountGet200Response()

        // to test the property `total`
        should("test total") {
            // uncomment below to test the property
            //modelInstance.total shouldBe ("TODO")
        }

        // to test the property `video`
        should("test video") {
            // uncomment below to test the property
            //modelInstance.video shouldBe ("TODO")
        }

        // to test the property `audio`
        should("test audio") {
            // uncomment below to test the property
            //modelInstance.audio shouldBe ("TODO")
        }

        // to test the property `subtitles`
        should("test subtitles") {
            // uncomment below to test the property
            //modelInstance.subtitles shouldBe ("TODO")
        }

        // to test the property `others`
        should("test others") {
            // uncomment below to test the property
            //modelInstance.others shouldBe ("TODO")
        }

        // to test the property ``open``
        should("test `open`") {
            // uncomment below to test the property
            //modelInstance.`open` shouldBe ("TODO")
        }

        // to test the property `closed`
        should("test closed") {
            // uncomment below to test the property
            //modelInstance.closed shouldBe ("TODO")
        }

    }
}
