/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.IssuePostRequest

class IssuePostRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of IssuePostRequest
        //val modelInstance = IssuePostRequest()

        // to test the property `issueType`
        should("test issueType") {
            // uncomment below to test the property
            //modelInstance.issueType shouldBe ("TODO")
        }

        // to test the property `message`
        should("test message") {
            // uncomment below to test the property
            //modelInstance.message shouldBe ("TODO")
        }

        // to test the property `mediaId`
        should("test mediaId") {
            // uncomment below to test the property
            //modelInstance.mediaId shouldBe ("TODO")
        }

    }
}
