/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.LanguagesGet200ResponseInner

class LanguagesGet200ResponseInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LanguagesGet200ResponseInner
        //val modelInstance = LanguagesGet200ResponseInner()

        // to test the property `iso6391`
        should("test iso6391") {
            // uncomment below to test the property
            //modelInstance.iso6391 shouldBe ("TODO")
        }

        // to test the property `englishName`
        should("test englishName") {
            // uncomment below to test the property
            //modelInstance.englishName shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

    }
}
