/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.MainSettings

class MainSettingsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MainSettings
        //val modelInstance = MainSettings()

        // to test the property `apiKey`
        should("test apiKey") {
            // uncomment below to test the property
            //modelInstance.apiKey shouldBe ("TODO")
        }

        // to test the property `appLanguage`
        should("test appLanguage") {
            // uncomment below to test the property
            //modelInstance.appLanguage shouldBe ("TODO")
        }

        // to test the property `applicationTitle`
        should("test applicationTitle") {
            // uncomment below to test the property
            //modelInstance.applicationTitle shouldBe ("TODO")
        }

        // to test the property `applicationUrl`
        should("test applicationUrl") {
            // uncomment below to test the property
            //modelInstance.applicationUrl shouldBe ("TODO")
        }

        // to test the property `hideAvailable`
        should("test hideAvailable") {
            // uncomment below to test the property
            //modelInstance.hideAvailable shouldBe ("TODO")
        }

        // to test the property `partialRequestsEnabled`
        should("test partialRequestsEnabled") {
            // uncomment below to test the property
            //modelInstance.partialRequestsEnabled shouldBe ("TODO")
        }

        // to test the property `localLogin`
        should("test localLogin") {
            // uncomment below to test the property
            //modelInstance.localLogin shouldBe ("TODO")
        }

        // to test the property `mediaServerType`
        should("test mediaServerType") {
            // uncomment below to test the property
            //modelInstance.mediaServerType shouldBe ("TODO")
        }

        // to test the property `newPlexLogin`
        should("test newPlexLogin") {
            // uncomment below to test the property
            //modelInstance.newPlexLogin shouldBe ("TODO")
        }

        // to test the property `defaultPermissions`
        should("test defaultPermissions") {
            // uncomment below to test the property
            //modelInstance.defaultPermissions shouldBe ("TODO")
        }

        // to test the property `enableSpecialEpisodes`
        should("test enableSpecialEpisodes") {
            // uncomment below to test the property
            //modelInstance.enableSpecialEpisodes shouldBe ("TODO")
        }

    }
}
