/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.MediaRequest
import com.lowiq.jellyfish.jellyseer.models.MediaInfo
import com.lowiq.jellyfish.jellyseer.models.MediaRequestModifiedBy
import com.lowiq.jellyfish.jellyseer.models.User

class MediaRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MediaRequest
        //val modelInstance = MediaRequest()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `status` - Status of the request. 1 = PENDING APPROVAL, 2 = APPROVED, 3 = DECLINED
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `media`
        should("test media") {
            // uncomment below to test the property
            //modelInstance.media shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `updatedAt`
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `requestedBy`
        should("test requestedBy") {
            // uncomment below to test the property
            //modelInstance.requestedBy shouldBe ("TODO")
        }

        // to test the property `modifiedBy`
        should("test modifiedBy") {
            // uncomment below to test the property
            //modelInstance.modifiedBy shouldBe ("TODO")
        }

        // to test the property `is4k`
        should("test is4k") {
            // uncomment below to test the property
            //modelInstance.is4k shouldBe ("TODO")
        }

        // to test the property `serverId`
        should("test serverId") {
            // uncomment below to test the property
            //modelInstance.serverId shouldBe ("TODO")
        }

        // to test the property `profileId`
        should("test profileId") {
            // uncomment below to test the property
            //modelInstance.profileId shouldBe ("TODO")
        }

        // to test the property `rootFolder`
        should("test rootFolder") {
            // uncomment below to test the property
            //modelInstance.rootFolder shouldBe ("TODO")
        }

    }
}
