/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.MediaMediaIdWatchDataGet200Response
import com.lowiq.jellyfish.jellyseer.models.MediaMediaIdWatchDataGet200ResponseData

class MediaMediaIdWatchDataGet200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MediaMediaIdWatchDataGet200Response
        //val modelInstance = MediaMediaIdWatchDataGet200Response()

        // to test the property ``data``
        should("test `data`") {
            // uncomment below to test the property
            //modelInstance.`data` shouldBe ("TODO")
        }

        // to test the property `data4k`
        should("test data4k") {
            // uncomment below to test the property
            //modelInstance.data4k shouldBe ("TODO")
        }

    }
}
