/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.MediaMediaIdWatchDataGet200ResponseData
import com.lowiq.jellyfish.jellyseer.models.User

class MediaMediaIdWatchDataGet200ResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MediaMediaIdWatchDataGet200ResponseData
        //val modelInstance = MediaMediaIdWatchDataGet200ResponseData()

        // to test the property `playCount7Days`
        should("test playCount7Days") {
            // uncomment below to test the property
            //modelInstance.playCount7Days shouldBe ("TODO")
        }

        // to test the property `playCount30Days`
        should("test playCount30Days") {
            // uncomment below to test the property
            //modelInstance.playCount30Days shouldBe ("TODO")
        }

        // to test the property `playCount`
        should("test playCount") {
            // uncomment below to test the property
            //modelInstance.playCount shouldBe ("TODO")
        }

        // to test the property `users`
        should("test users") {
            // uncomment below to test the property
            //modelInstance.users shouldBe ("TODO")
        }

    }
}
