/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.MediaMediaIdStatusPostRequest

class MediaMediaIdStatusPostRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MediaMediaIdStatusPostRequest
        //val modelInstance = MediaMediaIdStatusPostRequest()

        // to test the property `is4k` - When true, updates the 4K status field (status4k). When false or not provided, updates the regular status field (status). This applies to all status values (available, partial, processing, pending, unknown). 
        should("test is4k") {
            // uncomment below to test the property
            //modelInstance.is4k shouldBe ("TODO")
        }

    }
}
