/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.MetadataSettings
import com.lowiq.jellyfish.jellyseer.models.MetadataSettingsSettings

class MetadataSettingsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MetadataSettings
        //val modelInstance = MetadataSettings()

        // to test the property `settings`
        should("test settings") {
            // uncomment below to test the property
            //modelInstance.settings shouldBe ("TODO")
        }

    }
}
