/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.MovieDetailsCredits
import com.lowiq.jellyfish.jellyseer.models.Cast
import com.lowiq.jellyfish.jellyseer.models.Crew

class MovieDetailsCreditsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MovieDetailsCredits
        //val modelInstance = MovieDetailsCredits()

        // to test the property `cast`
        should("test cast") {
            // uncomment below to test the property
            //modelInstance.cast shouldBe ("TODO")
        }

        // to test the property `crew`
        should("test crew") {
            // uncomment below to test the property
            //modelInstance.crew shouldBe ("TODO")
        }

    }
}
