/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.MovieMovieIdRatingsGet200Response

class MovieMovieIdRatingsGet200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MovieMovieIdRatingsGet200Response
        //val modelInstance = MovieMovieIdRatingsGet200Response()

        // to test the property `title`
        should("test title") {
            // uncomment below to test the property
            //modelInstance.title shouldBe ("TODO")
        }

        // to test the property `year`
        should("test year") {
            // uncomment below to test the property
            //modelInstance.year shouldBe ("TODO")
        }

        // to test the property `url`
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

        // to test the property `criticsScore`
        should("test criticsScore") {
            // uncomment below to test the property
            //modelInstance.criticsScore shouldBe ("TODO")
        }

        // to test the property `criticsRating`
        should("test criticsRating") {
            // uncomment below to test the property
            //modelInstance.criticsRating shouldBe ("TODO")
        }

        // to test the property `audienceScore`
        should("test audienceScore") {
            // uncomment below to test the property
            //modelInstance.audienceScore shouldBe ("TODO")
        }

        // to test the property `audienceRating`
        should("test audienceRating") {
            // uncomment below to test the property
            //modelInstance.audienceRating shouldBe ("TODO")
        }

    }
}
