/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.MovieDetailsProductionCountriesInner

class MovieDetailsProductionCountriesInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MovieDetailsProductionCountriesInner
        //val modelInstance = MovieDetailsProductionCountriesInner()

        // to test the property `iso31661`
        should("test iso31661") {
            // uncomment below to test the property
            //modelInstance.iso31661 shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

    }
}
