/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.MovieDetailsReleasesResultsInnerReleaseDatesInner

class MovieDetailsReleasesResultsInnerReleaseDatesInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MovieDetailsReleasesResultsInnerReleaseDatesInner
        //val modelInstance = MovieDetailsReleasesResultsInnerReleaseDatesInner()

        // to test the property `certification`
        should("test certification") {
            // uncomment below to test the property
            //modelInstance.certification shouldBe ("TODO")
        }

        // to test the property `iso6391`
        should("test iso6391") {
            // uncomment below to test the property
            //modelInstance.iso6391 shouldBe ("TODO")
        }

        // to test the property `note`
        should("test note") {
            // uncomment below to test the property
            //modelInstance.note shouldBe ("TODO")
        }

        // to test the property `releaseDate`
        should("test releaseDate") {
            // uncomment below to test the property
            //modelInstance.releaseDate shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

    }
}
