/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.NetworkSettings
import com.lowiq.jellyfish.jellyseer.models.NetworkSettingsDnsCache
import com.lowiq.jellyfish.jellyseer.models.NetworkSettingsProxy

class NetworkSettingsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of NetworkSettings
        //val modelInstance = NetworkSettings()

        // to test the property `csrfProtection`
        should("test csrfProtection") {
            // uncomment below to test the property
            //modelInstance.csrfProtection shouldBe ("TODO")
        }

        // to test the property `forceIpv4First`
        should("test forceIpv4First") {
            // uncomment below to test the property
            //modelInstance.forceIpv4First shouldBe ("TODO")
        }

        // to test the property `trustProxy`
        should("test trustProxy") {
            // uncomment below to test the property
            //modelInstance.trustProxy shouldBe ("TODO")
        }

        // to test the property `proxy`
        should("test proxy") {
            // uncomment below to test the property
            //modelInstance.proxy shouldBe ("TODO")
        }

        // to test the property `dnsCache`
        should("test dnsCache") {
            // uncomment below to test the property
            //modelInstance.dnsCache shouldBe ("TODO")
        }

    }
}
