/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.NetworkSettingsProxy

class NetworkSettingsProxyTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of NetworkSettingsProxy
        //val modelInstance = NetworkSettingsProxy()

        // to test the property `enabled`
        should("test enabled") {
            // uncomment below to test the property
            //modelInstance.enabled shouldBe ("TODO")
        }

        // to test the property `hostname`
        should("test hostname") {
            // uncomment below to test the property
            //modelInstance.hostname shouldBe ("TODO")
        }

        // to test the property `port`
        should("test port") {
            // uncomment below to test the property
            //modelInstance.port shouldBe ("TODO")
        }

        // to test the property `useSsl`
        should("test useSsl") {
            // uncomment below to test the property
            //modelInstance.useSsl shouldBe ("TODO")
        }

        // to test the property `user`
        should("test user") {
            // uncomment below to test the property
            //modelInstance.user shouldBe ("TODO")
        }

        // to test the property `password`
        should("test password") {
            // uncomment below to test the property
            //modelInstance.password shouldBe ("TODO")
        }

        // to test the property `bypassFilter`
        should("test bypassFilter") {
            // uncomment below to test the property
            //modelInstance.bypassFilter shouldBe ("TODO")
        }

        // to test the property `bypassLocalAddresses`
        should("test bypassLocalAddresses") {
            // uncomment below to test the property
            //modelInstance.bypassLocalAddresses shouldBe ("TODO")
        }

    }
}
