/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.NotificationEmailSettingsOptions

class NotificationEmailSettingsOptionsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of NotificationEmailSettingsOptions
        //val modelInstance = NotificationEmailSettingsOptions()

        // to test the property `emailFrom`
        should("test emailFrom") {
            // uncomment below to test the property
            //modelInstance.emailFrom shouldBe ("TODO")
        }

        // to test the property `senderName`
        should("test senderName") {
            // uncomment below to test the property
            //modelInstance.senderName shouldBe ("TODO")
        }

        // to test the property `smtpHost`
        should("test smtpHost") {
            // uncomment below to test the property
            //modelInstance.smtpHost shouldBe ("TODO")
        }

        // to test the property `smtpPort`
        should("test smtpPort") {
            // uncomment below to test the property
            //modelInstance.smtpPort shouldBe ("TODO")
        }

        // to test the property `secure`
        should("test secure") {
            // uncomment below to test the property
            //modelInstance.secure shouldBe ("TODO")
        }

        // to test the property `ignoreTls`
        should("test ignoreTls") {
            // uncomment below to test the property
            //modelInstance.ignoreTls shouldBe ("TODO")
        }

        // to test the property `requireTls`
        should("test requireTls") {
            // uncomment below to test the property
            //modelInstance.requireTls shouldBe ("TODO")
        }

        // to test the property `authUser`
        should("test authUser") {
            // uncomment below to test the property
            //modelInstance.authUser shouldBe ("TODO")
        }

        // to test the property `authPass`
        should("test authPass") {
            // uncomment below to test the property
            //modelInstance.authPass shouldBe ("TODO")
        }

        // to test the property `allowSelfSigned`
        should("test allowSelfSigned") {
            // uncomment below to test the property
            //modelInstance.allowSelfSigned shouldBe ("TODO")
        }

    }
}
