/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.NotificationAgentTypes

class NotificationAgentTypesTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of NotificationAgentTypes
        //val modelInstance = NotificationAgentTypes()

        // to test the property `discord`
        should("test discord") {
            // uncomment below to test the property
            //modelInstance.discord shouldBe ("TODO")
        }

        // to test the property `email`
        should("test email") {
            // uncomment below to test the property
            //modelInstance.email shouldBe ("TODO")
        }

        // to test the property `pushbullet`
        should("test pushbullet") {
            // uncomment below to test the property
            //modelInstance.pushbullet shouldBe ("TODO")
        }

        // to test the property `pushover`
        should("test pushover") {
            // uncomment below to test the property
            //modelInstance.pushover shouldBe ("TODO")
        }

        // to test the property `slack`
        should("test slack") {
            // uncomment below to test the property
            //modelInstance.slack shouldBe ("TODO")
        }

        // to test the property `telegram`
        should("test telegram") {
            // uncomment below to test the property
            //modelInstance.telegram shouldBe ("TODO")
        }

        // to test the property `webhook`
        should("test webhook") {
            // uncomment below to test the property
            //modelInstance.webhook shouldBe ("TODO")
        }

        // to test the property `webpush`
        should("test webpush") {
            // uncomment below to test the property
            //modelInstance.webpush shouldBe ("TODO")
        }

    }
}
