/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.PersonResult
import com.lowiq.jellyfish.jellyseer.models.PersonResultKnownForInner

class PersonResultTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PersonResult
        //val modelInstance = PersonResult()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `profilePath`
        should("test profilePath") {
            // uncomment below to test the property
            //modelInstance.profilePath shouldBe ("TODO")
        }

        // to test the property `adult`
        should("test adult") {
            // uncomment below to test the property
            //modelInstance.adult shouldBe ("TODO")
        }

        // to test the property `mediaType`
        should("test mediaType") {
            // uncomment below to test the property
            //modelInstance.mediaType shouldBe ("TODO")
        }

        // to test the property `knownFor`
        should("test knownFor") {
            // uncomment below to test the property
            //modelInstance.knownFor shouldBe ("TODO")
        }

    }
}
