/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.PersonResultKnownForInner
import com.lowiq.jellyfish.jellyseer.models.MediaInfo
import com.lowiq.jellyfish.jellyseer.models.MovieResult
import com.lowiq.jellyfish.jellyseer.models.TvResult

class PersonResultKnownForInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PersonResultKnownForInner
        //val modelInstance = PersonResultKnownForInner()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `mediaType`
        should("test mediaType") {
            // uncomment below to test the property
            //modelInstance.mediaType shouldBe ("TODO")
        }

        // to test the property `title`
        should("test title") {
            // uncomment below to test the property
            //modelInstance.title shouldBe ("TODO")
        }

        // to test the property `popularity`
        should("test popularity") {
            // uncomment below to test the property
            //modelInstance.popularity shouldBe ("TODO")
        }

        // to test the property `posterPath`
        should("test posterPath") {
            // uncomment below to test the property
            //modelInstance.posterPath shouldBe ("TODO")
        }

        // to test the property `backdropPath`
        should("test backdropPath") {
            // uncomment below to test the property
            //modelInstance.backdropPath shouldBe ("TODO")
        }

        // to test the property `voteCount`
        should("test voteCount") {
            // uncomment below to test the property
            //modelInstance.voteCount shouldBe ("TODO")
        }

        // to test the property `voteAverage`
        should("test voteAverage") {
            // uncomment below to test the property
            //modelInstance.voteAverage shouldBe ("TODO")
        }

        // to test the property `genreIds`
        should("test genreIds") {
            // uncomment below to test the property
            //modelInstance.genreIds shouldBe ("TODO")
        }

        // to test the property `overview`
        should("test overview") {
            // uncomment below to test the property
            //modelInstance.overview shouldBe ("TODO")
        }

        // to test the property `originalLanguage`
        should("test originalLanguage") {
            // uncomment below to test the property
            //modelInstance.originalLanguage shouldBe ("TODO")
        }

        // to test the property `originalTitle`
        should("test originalTitle") {
            // uncomment below to test the property
            //modelInstance.originalTitle shouldBe ("TODO")
        }

        // to test the property `releaseDate`
        should("test releaseDate") {
            // uncomment below to test the property
            //modelInstance.releaseDate shouldBe ("TODO")
        }

        // to test the property `adult`
        should("test adult") {
            // uncomment below to test the property
            //modelInstance.adult shouldBe ("TODO")
        }

        // to test the property `video`
        should("test video") {
            // uncomment below to test the property
            //modelInstance.video shouldBe ("TODO")
        }

        // to test the property `mediaInfo`
        should("test mediaInfo") {
            // uncomment below to test the property
            //modelInstance.mediaInfo shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `originalName`
        should("test originalName") {
            // uncomment below to test the property
            //modelInstance.originalName shouldBe ("TODO")
        }

        // to test the property `originCountry`
        should("test originCountry") {
            // uncomment below to test the property
            //modelInstance.originCountry shouldBe ("TODO")
        }

        // to test the property `firstAirDate`
        should("test firstAirDate") {
            // uncomment below to test the property
            //modelInstance.firstAirDate shouldBe ("TODO")
        }

    }
}
