/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.PlexDevice
import com.lowiq.jellyfish.jellyseer.models.PlexConnection

class PlexDeviceTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PlexDevice
        //val modelInstance = PlexDevice()

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `product`
        should("test product") {
            // uncomment below to test the property
            //modelInstance.product shouldBe ("TODO")
        }

        // to test the property `productVersion`
        should("test productVersion") {
            // uncomment below to test the property
            //modelInstance.productVersion shouldBe ("TODO")
        }

        // to test the property `platform`
        should("test platform") {
            // uncomment below to test the property
            //modelInstance.platform shouldBe ("TODO")
        }

        // to test the property `device`
        should("test device") {
            // uncomment below to test the property
            //modelInstance.device shouldBe ("TODO")
        }

        // to test the property `clientIdentifier`
        should("test clientIdentifier") {
            // uncomment below to test the property
            //modelInstance.clientIdentifier shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `lastSeenAt`
        should("test lastSeenAt") {
            // uncomment below to test the property
            //modelInstance.lastSeenAt shouldBe ("TODO")
        }

        // to test the property `provides`
        should("test provides") {
            // uncomment below to test the property
            //modelInstance.provides shouldBe ("TODO")
        }

        // to test the property `owned`
        should("test owned") {
            // uncomment below to test the property
            //modelInstance.owned shouldBe ("TODO")
        }

        // to test the property `connection`
        should("test connection") {
            // uncomment below to test the property
            //modelInstance.connection shouldBe ("TODO")
        }

        // to test the property `platformVersion`
        should("test platformVersion") {
            // uncomment below to test the property
            //modelInstance.platformVersion shouldBe ("TODO")
        }

        // to test the property `ownerID`
        should("test ownerID") {
            // uncomment below to test the property
            //modelInstance.ownerID shouldBe ("TODO")
        }

        // to test the property `home`
        should("test home") {
            // uncomment below to test the property
            //modelInstance.home shouldBe ("TODO")
        }

        // to test the property `sourceTitle`
        should("test sourceTitle") {
            // uncomment below to test the property
            //modelInstance.sourceTitle shouldBe ("TODO")
        }

        // to test the property `accessToken`
        should("test accessToken") {
            // uncomment below to test the property
            //modelInstance.accessToken shouldBe ("TODO")
        }

        // to test the property `publicAddress`
        should("test publicAddress") {
            // uncomment below to test the property
            //modelInstance.publicAddress shouldBe ("TODO")
        }

        // to test the property `httpsRequired`
        should("test httpsRequired") {
            // uncomment below to test the property
            //modelInstance.httpsRequired shouldBe ("TODO")
        }

        // to test the property `synced`
        should("test synced") {
            // uncomment below to test the property
            //modelInstance.synced shouldBe ("TODO")
        }

        // to test the property `relay`
        should("test relay") {
            // uncomment below to test the property
            //modelInstance.relay shouldBe ("TODO")
        }

        // to test the property `dnsRebindingProtection`
        should("test dnsRebindingProtection") {
            // uncomment below to test the property
            //modelInstance.dnsRebindingProtection shouldBe ("TODO")
        }

        // to test the property `natLoopbackSupported`
        should("test natLoopbackSupported") {
            // uncomment below to test the property
            //modelInstance.natLoopbackSupported shouldBe ("TODO")
        }

        // to test the property `publicAddressMatches`
        should("test publicAddressMatches") {
            // uncomment below to test the property
            //modelInstance.publicAddressMatches shouldBe ("TODO")
        }

        // to test the property `presence`
        should("test presence") {
            // uncomment below to test the property
            //modelInstance.presence shouldBe ("TODO")
        }

    }
}
