/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.PlexSettings
import com.lowiq.jellyfish.jellyseer.models.PlexLibrary

class PlexSettingsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PlexSettings
        //val modelInstance = PlexSettings()

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `machineId`
        should("test machineId") {
            // uncomment below to test the property
            //modelInstance.machineId shouldBe ("TODO")
        }

        // to test the property `ip`
        should("test ip") {
            // uncomment below to test the property
            //modelInstance.ip shouldBe ("TODO")
        }

        // to test the property `port`
        should("test port") {
            // uncomment below to test the property
            //modelInstance.port shouldBe ("TODO")
        }

        // to test the property `useSsl`
        should("test useSsl") {
            // uncomment below to test the property
            //modelInstance.useSsl shouldBe ("TODO")
        }

        // to test the property `libraries`
        should("test libraries") {
            // uncomment below to test the property
            //modelInstance.libraries shouldBe ("TODO")
        }

        // to test the property `webAppUrl`
        should("test webAppUrl") {
            // uncomment below to test the property
            //modelInstance.webAppUrl shouldBe ("TODO")
        }

    }
}
