/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.PushoverSettings
import com.lowiq.jellyfish.jellyseer.models.PushoverSettingsOptions

class PushoverSettingsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PushoverSettings
        //val modelInstance = PushoverSettings()

        // to test the property `enabled`
        should("test enabled") {
            // uncomment below to test the property
            //modelInstance.enabled shouldBe ("TODO")
        }

        // to test the property `types`
        should("test types") {
            // uncomment below to test the property
            //modelInstance.types shouldBe ("TODO")
        }

        // to test the property `options`
        should("test options") {
            // uncomment below to test the property
            //modelInstance.options shouldBe ("TODO")
        }

    }
}
