/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.PushbulletSettingsOptions

class PushbulletSettingsOptionsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PushbulletSettingsOptions
        //val modelInstance = PushbulletSettingsOptions()

        // to test the property `accessToken`
        should("test accessToken") {
            // uncomment below to test the property
            //modelInstance.accessToken shouldBe ("TODO")
        }

        // to test the property `channelTag`
        should("test channelTag") {
            // uncomment below to test the property
            //modelInstance.channelTag shouldBe ("TODO")
        }

    }
}
