/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.PushoverSettingsOptions

class PushoverSettingsOptionsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PushoverSettingsOptions
        //val modelInstance = PushoverSettingsOptions()

        // to test the property `accessToken`
        should("test accessToken") {
            // uncomment below to test the property
            //modelInstance.accessToken shouldBe ("TODO")
        }

        // to test the property `userToken`
        should("test userToken") {
            // uncomment below to test the property
            //modelInstance.userToken shouldBe ("TODO")
        }

        // to test the property `sound`
        should("test sound") {
            // uncomment below to test the property
            //modelInstance.sound shouldBe ("TODO")
        }

    }
}
