/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.RadarrSettings

class RadarrSettingsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RadarrSettings
        //val modelInstance = RadarrSettings()

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `hostname`
        should("test hostname") {
            // uncomment below to test the property
            //modelInstance.hostname shouldBe ("TODO")
        }

        // to test the property `port`
        should("test port") {
            // uncomment below to test the property
            //modelInstance.port shouldBe ("TODO")
        }

        // to test the property `apiKey`
        should("test apiKey") {
            // uncomment below to test the property
            //modelInstance.apiKey shouldBe ("TODO")
        }

        // to test the property `useSsl`
        should("test useSsl") {
            // uncomment below to test the property
            //modelInstance.useSsl shouldBe ("TODO")
        }

        // to test the property `activeProfileId`
        should("test activeProfileId") {
            // uncomment below to test the property
            //modelInstance.activeProfileId shouldBe ("TODO")
        }

        // to test the property `activeProfileName`
        should("test activeProfileName") {
            // uncomment below to test the property
            //modelInstance.activeProfileName shouldBe ("TODO")
        }

        // to test the property `activeDirectory`
        should("test activeDirectory") {
            // uncomment below to test the property
            //modelInstance.activeDirectory shouldBe ("TODO")
        }

        // to test the property `is4k`
        should("test is4k") {
            // uncomment below to test the property
            //modelInstance.is4k shouldBe ("TODO")
        }

        // to test the property `minimumAvailability`
        should("test minimumAvailability") {
            // uncomment below to test the property
            //modelInstance.minimumAvailability shouldBe ("TODO")
        }

        // to test the property `isDefault`
        should("test isDefault") {
            // uncomment below to test the property
            //modelInstance.isDefault shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `baseUrl`
        should("test baseUrl") {
            // uncomment below to test the property
            //modelInstance.baseUrl shouldBe ("TODO")
        }

        // to test the property `externalUrl`
        should("test externalUrl") {
            // uncomment below to test the property
            //modelInstance.externalUrl shouldBe ("TODO")
        }

        // to test the property `syncEnabled`
        should("test syncEnabled") {
            // uncomment below to test the property
            //modelInstance.syncEnabled shouldBe ("TODO")
        }

        // to test the property `preventSearch`
        should("test preventSearch") {
            // uncomment below to test the property
            //modelInstance.preventSearch shouldBe ("TODO")
        }

    }
}
