/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.RequestRequestIdPutRequest

class RequestRequestIdPutRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RequestRequestIdPutRequest
        //val modelInstance = RequestRequestIdPutRequest()

        // to test the property `mediaType`
        should("test mediaType") {
            // uncomment below to test the property
            //modelInstance.mediaType shouldBe ("TODO")
        }

        // to test the property `seasons`
        should("test seasons") {
            // uncomment below to test the property
            //modelInstance.seasons shouldBe ("TODO")
        }

        // to test the property `is4k`
        should("test is4k") {
            // uncomment below to test the property
            //modelInstance.is4k shouldBe ("TODO")
        }

        // to test the property `serverId`
        should("test serverId") {
            // uncomment below to test the property
            //modelInstance.serverId shouldBe ("TODO")
        }

        // to test the property `profileId`
        should("test profileId") {
            // uncomment below to test the property
            //modelInstance.profileId shouldBe ("TODO")
        }

        // to test the property `rootFolder`
        should("test rootFolder") {
            // uncomment below to test the property
            //modelInstance.rootFolder shouldBe ("TODO")
        }

        // to test the property `languageProfileId`
        should("test languageProfileId") {
            // uncomment below to test the property
            //modelInstance.languageProfileId shouldBe ("TODO")
        }

        // to test the property `userId`
        should("test userId") {
            // uncomment below to test the property
            //modelInstance.userId shouldBe ("TODO")
        }

    }
}
