/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.RequestCountGet200Response

class RequestCountGet200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RequestCountGet200Response
        //val modelInstance = RequestCountGet200Response()

        // to test the property `total`
        should("test total") {
            // uncomment below to test the property
            //modelInstance.total shouldBe ("TODO")
        }

        // to test the property `movie`
        should("test movie") {
            // uncomment below to test the property
            //modelInstance.movie shouldBe ("TODO")
        }

        // to test the property `tv`
        should("test tv") {
            // uncomment below to test the property
            //modelInstance.tv shouldBe ("TODO")
        }

        // to test the property `pending`
        should("test pending") {
            // uncomment below to test the property
            //modelInstance.pending shouldBe ("TODO")
        }

        // to test the property `approved`
        should("test approved") {
            // uncomment below to test the property
            //modelInstance.approved shouldBe ("TODO")
        }

        // to test the property `declined`
        should("test declined") {
            // uncomment below to test the property
            //modelInstance.declined shouldBe ("TODO")
        }

        // to test the property `processing`
        should("test processing") {
            // uncomment below to test the property
            //modelInstance.processing shouldBe ("TODO")
        }

        // to test the property `available`
        should("test available") {
            // uncomment below to test the property
            //modelInstance.available shouldBe ("TODO")
        }

        // to test the property `completed`
        should("test completed") {
            // uncomment below to test the property
            //modelInstance.completed shouldBe ("TODO")
        }

    }
}
