/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.SettingsCacheGet200ResponseDnsCacheStats

class SettingsCacheGet200ResponseDnsCacheStatsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SettingsCacheGet200ResponseDnsCacheStats
        //val modelInstance = SettingsCacheGet200ResponseDnsCacheStats()

        // to test the property `propertySize`
        should("test propertySize") {
            // uncomment below to test the property
            //modelInstance.propertySize shouldBe ("TODO")
        }

        // to test the property `maxSize`
        should("test maxSize") {
            // uncomment below to test the property
            //modelInstance.maxSize shouldBe ("TODO")
        }

        // to test the property `hits`
        should("test hits") {
            // uncomment below to test the property
            //modelInstance.hits shouldBe ("TODO")
        }

        // to test the property `misses`
        should("test misses") {
            // uncomment below to test the property
            //modelInstance.misses shouldBe ("TODO")
        }

        // to test the property `failures`
        should("test failures") {
            // uncomment below to test the property
            //modelInstance.failures shouldBe ("TODO")
        }

        // to test the property `ipv4Fallbacks`
        should("test ipv4Fallbacks") {
            // uncomment below to test the property
            //modelInstance.ipv4Fallbacks shouldBe ("TODO")
        }

        // to test the property `hitRate`
        should("test hitRate") {
            // uncomment below to test the property
            //modelInstance.hitRate shouldBe ("TODO")
        }

    }
}
