/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.SettingsDiscoverAddPostRequest

class SettingsDiscoverAddPostRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SettingsDiscoverAddPostRequest
        //val modelInstance = SettingsDiscoverAddPostRequest()

        // to test the property `title`
        should("test title") {
            // uncomment below to test the property
            //modelInstance.title shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property ``data``
        should("test `data`") {
            // uncomment below to test the property
            //modelInstance.`data` shouldBe ("TODO")
        }

    }
}
