/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.SettingsRadarrTestPost200Response
import com.lowiq.jellyfish.jellyseer.models.ServiceProfile

class SettingsRadarrTestPost200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SettingsRadarrTestPost200Response
        //val modelInstance = SettingsRadarrTestPost200Response()

        // to test the property `profiles`
        should("test profiles") {
            // uncomment below to test the property
            //modelInstance.profiles shouldBe ("TODO")
        }

    }
}
