/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.SettingsAboutGet200Response

class SettingsAboutGet200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SettingsAboutGet200Response
        //val modelInstance = SettingsAboutGet200Response()

        // to test the property `version`
        should("test version") {
            // uncomment below to test the property
            //modelInstance.version shouldBe ("TODO")
        }

        // to test the property `totalRequests`
        should("test totalRequests") {
            // uncomment below to test the property
            //modelInstance.totalRequests shouldBe ("TODO")
        }

        // to test the property `totalMediaItems`
        should("test totalMediaItems") {
            // uncomment below to test the property
            //modelInstance.totalMediaItems shouldBe ("TODO")
        }

        // to test the property `tz`
        should("test tz") {
            // uncomment below to test the property
            //modelInstance.tz shouldBe ("TODO")
        }

        // to test the property `appDataPath`
        should("test appDataPath") {
            // uncomment below to test the property
            //modelInstance.appDataPath shouldBe ("TODO")
        }

    }
}
