/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.SettingsCacheGet200ResponseDnsCacheEntriesValueAddresses

class SettingsCacheGet200ResponseDnsCacheEntriesValueAddressesTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SettingsCacheGet200ResponseDnsCacheEntriesValueAddresses
        //val modelInstance = SettingsCacheGet200ResponseDnsCacheEntriesValueAddresses()

        // to test the property `ipv4`
        should("test ipv4") {
            // uncomment below to test the property
            //modelInstance.ipv4 shouldBe ("TODO")
        }

        // to test the property `ipv6`
        should("test ipv6") {
            // uncomment below to test the property
            //modelInstance.ipv6 shouldBe ("TODO")
        }

    }
}
