/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.SettingsMetadatasTestPostRequest

class SettingsMetadatasTestPostRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SettingsMetadatasTestPostRequest
        //val modelInstance = SettingsMetadatasTestPostRequest()

        // to test the property `tmdb`
        should("test tmdb") {
            // uncomment below to test the property
            //modelInstance.tmdb shouldBe ("TODO")
        }

        // to test the property `tvdb`
        should("test tvdb") {
            // uncomment below to test the property
            //modelInstance.tvdb shouldBe ("TODO")
        }

    }
}
