/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.SettingsCacheGet200ResponseDnsCache
import com.lowiq.jellyfish.jellyseer.models.SettingsCacheGet200ResponseDnsCacheEntriesValue
import com.lowiq.jellyfish.jellyseer.models.SettingsCacheGet200ResponseDnsCacheStats

class SettingsCacheGet200ResponseDnsCacheTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SettingsCacheGet200ResponseDnsCache
        //val modelInstance = SettingsCacheGet200ResponseDnsCache()

        // to test the property `stats`
        should("test stats") {
            // uncomment below to test the property
            //modelInstance.stats shouldBe ("TODO")
        }

        // to test the property `propertyEntries`
        should("test propertyEntries") {
            // uncomment below to test the property
            //modelInstance.propertyEntries shouldBe ("TODO")
        }

    }
}
