/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.SettingsJobsJobIdSchedulePostRequest

class SettingsJobsJobIdSchedulePostRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SettingsJobsJobIdSchedulePostRequest
        //val modelInstance = SettingsJobsJobIdSchedulePostRequest()

        // to test the property `schedule`
        should("test schedule") {
            // uncomment below to test the property
            //modelInstance.schedule shouldBe ("TODO")
        }

    }
}
