/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.SettingsCacheGet200ResponseImageCache
import com.lowiq.jellyfish.jellyseer.models.SettingsCacheGet200ResponseImageCacheTmdb

class SettingsCacheGet200ResponseImageCacheTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SettingsCacheGet200ResponseImageCache
        //val modelInstance = SettingsCacheGet200ResponseImageCache()

        // to test the property `tmdb`
        should("test tmdb") {
            // uncomment below to test the property
            //modelInstance.tmdb shouldBe ("TODO")
        }

        // to test the property `avatar`
        should("test avatar") {
            // uncomment below to test the property
            //modelInstance.avatar shouldBe ("TODO")
        }

    }
}
