/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.SlackSettingsOptions

class SlackSettingsOptionsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SlackSettingsOptions
        //val modelInstance = SlackSettingsOptions()

        // to test the property `webhookUrl`
        should("test webhookUrl") {
            // uncomment below to test the property
            //modelInstance.webhookUrl shouldBe ("TODO")
        }

    }
}
