/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.SonarrSeriesImagesInner

class SonarrSeriesImagesInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SonarrSeriesImagesInner
        //val modelInstance = SonarrSeriesImagesInner()

        // to test the property `coverType`
        should("test coverType") {
            // uncomment below to test the property
            //modelInstance.coverType shouldBe ("TODO")
        }

        // to test the property `url`
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

    }
}
