/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.SonarrSeriesSeasonsInner

class SonarrSeriesSeasonsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SonarrSeriesSeasonsInner
        //val modelInstance = SonarrSeriesSeasonsInner()

        // to test the property `seasonNumber`
        should("test seasonNumber") {
            // uncomment below to test the property
            //modelInstance.seasonNumber shouldBe ("TODO")
        }

        // to test the property `monitored`
        should("test monitored") {
            // uncomment below to test the property
            //modelInstance.monitored shouldBe ("TODO")
        }

    }
}
