/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.StatusGet200Response

class StatusGet200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StatusGet200Response
        //val modelInstance = StatusGet200Response()

        // to test the property `version`
        should("test version") {
            // uncomment below to test the property
            //modelInstance.version shouldBe ("TODO")
        }

        // to test the property `commitTag`
        should("test commitTag") {
            // uncomment below to test the property
            //modelInstance.commitTag shouldBe ("TODO")
        }

        // to test the property `updateAvailable`
        should("test updateAvailable") {
            // uncomment below to test the property
            //modelInstance.updateAvailable shouldBe ("TODO")
        }

        // to test the property `commitsBehind`
        should("test commitsBehind") {
            // uncomment below to test the property
            //modelInstance.commitsBehind shouldBe ("TODO")
        }

        // to test the property `restartRequired`
        should("test restartRequired") {
            // uncomment below to test the property
            //modelInstance.restartRequired shouldBe ("TODO")
        }

    }
}
