/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.TautulliSettings

class TautulliSettingsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TautulliSettings
        //val modelInstance = TautulliSettings()

        // to test the property `hostname`
        should("test hostname") {
            // uncomment below to test the property
            //modelInstance.hostname shouldBe ("TODO")
        }

        // to test the property `port`
        should("test port") {
            // uncomment below to test the property
            //modelInstance.port shouldBe ("TODO")
        }

        // to test the property `useSsl`
        should("test useSsl") {
            // uncomment below to test the property
            //modelInstance.useSsl shouldBe ("TODO")
        }

        // to test the property `apiKey`
        should("test apiKey") {
            // uncomment below to test the property
            //modelInstance.apiKey shouldBe ("TODO")
        }

        // to test the property `externalUrl`
        should("test externalUrl") {
            // uncomment below to test the property
            //modelInstance.externalUrl shouldBe ("TODO")
        }

    }
}
