/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.TelegramSettingsOptions

class TelegramSettingsOptionsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TelegramSettingsOptions
        //val modelInstance = TelegramSettingsOptions()

        // to test the property `botUsername`
        should("test botUsername") {
            // uncomment below to test the property
            //modelInstance.botUsername shouldBe ("TODO")
        }

        // to test the property `botAPI`
        should("test botAPI") {
            // uncomment below to test the property
            //modelInstance.botAPI shouldBe ("TODO")
        }

        // to test the property `chatId`
        should("test chatId") {
            // uncomment below to test the property
            //modelInstance.chatId shouldBe ("TODO")
        }

        // to test the property `messageThreadId`
        should("test messageThreadId") {
            // uncomment below to test the property
            //modelInstance.messageThreadId shouldBe ("TODO")
        }

        // to test the property `sendSilently`
        should("test sendSilently") {
            // uncomment below to test the property
            //modelInstance.sendSilently shouldBe ("TODO")
        }

    }
}
