/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.TvDetailsContentRatings
import com.lowiq.jellyfish.jellyseer.models.TvDetailsContentRatingsResultsInner

class TvDetailsContentRatingsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TvDetailsContentRatings
        //val modelInstance = TvDetailsContentRatings()

        // to test the property `results`
        should("test results") {
            // uncomment below to test the property
            //modelInstance.results shouldBe ("TODO")
        }

    }
}
