/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.UserUserIdSettingsPasswordGet200Response

class UserUserIdSettingsPasswordGet200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserUserIdSettingsPasswordGet200Response
        //val modelInstance = UserUserIdSettingsPasswordGet200Response()

        // to test the property `hasPassword`
        should("test hasPassword") {
            // uncomment below to test the property
            //modelInstance.hasPassword shouldBe ("TODO")
        }

    }
}
