/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.UserUserIdQuotaGet200ResponseMovie

class UserUserIdQuotaGet200ResponseMovieTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserUserIdQuotaGet200ResponseMovie
        //val modelInstance = UserUserIdQuotaGet200ResponseMovie()

        // to test the property `days`
        should("test days") {
            // uncomment below to test the property
            //modelInstance.days shouldBe ("TODO")
        }

        // to test the property `limit`
        should("test limit") {
            // uncomment below to test the property
            //modelInstance.limit shouldBe ("TODO")
        }

        // to test the property `used`
        should("test used") {
            // uncomment below to test the property
            //modelInstance.used shouldBe ("TODO")
        }

        // to test the property `remaining`
        should("test remaining") {
            // uncomment below to test the property
            //modelInstance.remaining shouldBe ("TODO")
        }

        // to test the property `restricted`
        should("test restricted") {
            // uncomment below to test the property
            //modelInstance.restricted shouldBe ("TODO")
        }

    }
}
