/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.UserUserIdSettingsPermissionsGet200Response

class UserUserIdSettingsPermissionsGet200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserUserIdSettingsPermissionsGet200Response
        //val modelInstance = UserUserIdSettingsPermissionsGet200Response()

        // to test the property `permissions`
        should("test permissions") {
            // uncomment below to test the property
            //modelInstance.permissions shouldBe ("TODO")
        }

    }
}
