/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.UserSettingsNotifications
import com.lowiq.jellyfish.jellyseer.models.NotificationAgentTypes

class UserSettingsNotificationsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserSettingsNotifications
        //val modelInstance = UserSettingsNotifications()

        // to test the property `notificationTypes`
        should("test notificationTypes") {
            // uncomment below to test the property
            //modelInstance.notificationTypes shouldBe ("TODO")
        }

        // to test the property `emailEnabled`
        should("test emailEnabled") {
            // uncomment below to test the property
            //modelInstance.emailEnabled shouldBe ("TODO")
        }

        // to test the property `pgpKey`
        should("test pgpKey") {
            // uncomment below to test the property
            //modelInstance.pgpKey shouldBe ("TODO")
        }

        // to test the property `discordEnabled`
        should("test discordEnabled") {
            // uncomment below to test the property
            //modelInstance.discordEnabled shouldBe ("TODO")
        }

        // to test the property `discordEnabledTypes`
        should("test discordEnabledTypes") {
            // uncomment below to test the property
            //modelInstance.discordEnabledTypes shouldBe ("TODO")
        }

        // to test the property `discordId`
        should("test discordId") {
            // uncomment below to test the property
            //modelInstance.discordId shouldBe ("TODO")
        }

        // to test the property `pushbulletAccessToken`
        should("test pushbulletAccessToken") {
            // uncomment below to test the property
            //modelInstance.pushbulletAccessToken shouldBe ("TODO")
        }

        // to test the property `pushoverApplicationToken`
        should("test pushoverApplicationToken") {
            // uncomment below to test the property
            //modelInstance.pushoverApplicationToken shouldBe ("TODO")
        }

        // to test the property `pushoverUserKey`
        should("test pushoverUserKey") {
            // uncomment below to test the property
            //modelInstance.pushoverUserKey shouldBe ("TODO")
        }

        // to test the property `pushoverSound`
        should("test pushoverSound") {
            // uncomment below to test the property
            //modelInstance.pushoverSound shouldBe ("TODO")
        }

        // to test the property `telegramEnabled`
        should("test telegramEnabled") {
            // uncomment below to test the property
            //modelInstance.telegramEnabled shouldBe ("TODO")
        }

        // to test the property `telegramBotUsername`
        should("test telegramBotUsername") {
            // uncomment below to test the property
            //modelInstance.telegramBotUsername shouldBe ("TODO")
        }

        // to test the property `telegramChatId`
        should("test telegramChatId") {
            // uncomment below to test the property
            //modelInstance.telegramChatId shouldBe ("TODO")
        }

        // to test the property `telegramMessageThreadId`
        should("test telegramMessageThreadId") {
            // uncomment below to test the property
            //modelInstance.telegramMessageThreadId shouldBe ("TODO")
        }

        // to test the property `telegramSendSilently`
        should("test telegramSendSilently") {
            // uncomment below to test the property
            //modelInstance.telegramSendSilently shouldBe ("TODO")
        }

    }
}
