/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.UserSettings

class UserSettingsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserSettings
        //val modelInstance = UserSettings()

        // to test the property `username`
        should("test username") {
            // uncomment below to test the property
            //modelInstance.username shouldBe ("TODO")
        }

        // to test the property `email`
        should("test email") {
            // uncomment below to test the property
            //modelInstance.email shouldBe ("TODO")
        }

        // to test the property `discordId`
        should("test discordId") {
            // uncomment below to test the property
            //modelInstance.discordId shouldBe ("TODO")
        }

        // to test the property `locale`
        should("test locale") {
            // uncomment below to test the property
            //modelInstance.locale shouldBe ("TODO")
        }

        // to test the property `discoverRegion`
        should("test discoverRegion") {
            // uncomment below to test the property
            //modelInstance.discoverRegion shouldBe ("TODO")
        }

        // to test the property `streamingRegion`
        should("test streamingRegion") {
            // uncomment below to test the property
            //modelInstance.streamingRegion shouldBe ("TODO")
        }

        // to test the property `originalLanguage`
        should("test originalLanguage") {
            // uncomment below to test the property
            //modelInstance.originalLanguage shouldBe ("TODO")
        }

        // to test the property `movieQuotaLimit` - Maximum number of movie requests allowed
        should("test movieQuotaLimit") {
            // uncomment below to test the property
            //modelInstance.movieQuotaLimit shouldBe ("TODO")
        }

        // to test the property `movieQuotaDays` - Time period in days for movie quota
        should("test movieQuotaDays") {
            // uncomment below to test the property
            //modelInstance.movieQuotaDays shouldBe ("TODO")
        }

        // to test the property `tvQuotaLimit` - Maximum number of TV requests allowed
        should("test tvQuotaLimit") {
            // uncomment below to test the property
            //modelInstance.tvQuotaLimit shouldBe ("TODO")
        }

        // to test the property `tvQuotaDays` - Time period in days for TV quota
        should("test tvQuotaDays") {
            // uncomment below to test the property
            //modelInstance.tvQuotaDays shouldBe ("TODO")
        }

        // to test the property `globalMovieQuotaDays` - Global movie quota days setting
        should("test globalMovieQuotaDays") {
            // uncomment below to test the property
            //modelInstance.globalMovieQuotaDays shouldBe ("TODO")
        }

        // to test the property `globalMovieQuotaLimit` - Global movie quota limit setting
        should("test globalMovieQuotaLimit") {
            // uncomment below to test the property
            //modelInstance.globalMovieQuotaLimit shouldBe ("TODO")
        }

        // to test the property `globalTvQuotaLimit` - Global TV quota limit setting
        should("test globalTvQuotaLimit") {
            // uncomment below to test the property
            //modelInstance.globalTvQuotaLimit shouldBe ("TODO")
        }

        // to test the property `globalTvQuotaDays` - Global TV quota days setting
        should("test globalTvQuotaDays") {
            // uncomment below to test the property
            //modelInstance.globalTvQuotaDays shouldBe ("TODO")
        }

        // to test the property `watchlistSyncMovies` - Enable watchlist sync for movies
        should("test watchlistSyncMovies") {
            // uncomment below to test the property
            //modelInstance.watchlistSyncMovies shouldBe ("TODO")
        }

        // to test the property `watchlistSyncTv` - Enable watchlist sync for TV
        should("test watchlistSyncTv") {
            // uncomment below to test the property
            //modelInstance.watchlistSyncTv shouldBe ("TODO")
        }

    }
}
