/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.User

class UserTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of User
        //val modelInstance = User()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `email`
        should("test email") {
            // uncomment below to test the property
            //modelInstance.email shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `updatedAt`
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `username`
        should("test username") {
            // uncomment below to test the property
            //modelInstance.username shouldBe ("TODO")
        }

        // to test the property `plexUsername`
        should("test plexUsername") {
            // uncomment below to test the property
            //modelInstance.plexUsername shouldBe ("TODO")
        }

        // to test the property `plexToken`
        should("test plexToken") {
            // uncomment below to test the property
            //modelInstance.plexToken shouldBe ("TODO")
        }

        // to test the property `jellyfinAuthToken`
        should("test jellyfinAuthToken") {
            // uncomment below to test the property
            //modelInstance.jellyfinAuthToken shouldBe ("TODO")
        }

        // to test the property `userType`
        should("test userType") {
            // uncomment below to test the property
            //modelInstance.userType shouldBe ("TODO")
        }

        // to test the property `permissions`
        should("test permissions") {
            // uncomment below to test the property
            //modelInstance.permissions shouldBe ("TODO")
        }

        // to test the property `avatar`
        should("test avatar") {
            // uncomment below to test the property
            //modelInstance.avatar shouldBe ("TODO")
        }

        // to test the property `requestCount`
        should("test requestCount") {
            // uncomment below to test the property
            //modelInstance.requestCount shouldBe ("TODO")
        }

    }
}
