/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.Watchlist
import com.lowiq.jellyfish.jellyseer.models.MediaInfo
import com.lowiq.jellyfish.jellyseer.models.User

class WatchlistTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Watchlist
        //val modelInstance = Watchlist()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `tmdbId`
        should("test tmdbId") {
            // uncomment below to test the property
            //modelInstance.tmdbId shouldBe ("TODO")
        }

        // to test the property `ratingKey`
        should("test ratingKey") {
            // uncomment below to test the property
            //modelInstance.ratingKey shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `title`
        should("test title") {
            // uncomment below to test the property
            //modelInstance.title shouldBe ("TODO")
        }

        // to test the property `media`
        should("test media") {
            // uncomment below to test the property
            //modelInstance.media shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `updatedAt`
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `requestedBy`
        should("test requestedBy") {
            // uncomment below to test the property
            //modelInstance.requestedBy shouldBe ("TODO")
        }

    }
}
