/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lowiq.jellyfish.jellyseer.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lowiq.jellyfish.jellyseer.models.WatchProviderRegion

class WatchProviderRegionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WatchProviderRegion
        //val modelInstance = WatchProviderRegion()

        // to test the property `iso31661`
        should("test iso31661") {
            // uncomment below to test the property
            //modelInstance.iso31661 shouldBe ("TODO")
        }

        // to test the property `englishName`
        should("test englishName") {
            // uncomment below to test the property
            //modelInstance.englishName shouldBe ("TODO")
        }

        // to test the property `nativeName`
        should("test nativeName") {
            // uncomment below to test the property
            //modelInstance.nativeName shouldBe ("TODO")
        }

    }
}
