name: Build Windows App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Permet de déclencher manuellement

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.4'
        channel: 'stable'
        
    - name: Enable Windows desktop
      run: flutter config --enable-windows-desktop
      
    - name: Install dependencies
      run: flutter pub get
      
    - name: Generate code (build_runner)
      run: flutter packages pub run build_runner build --delete-conflicting-outputs
      continue-on-error: true

    - name: Build Windows app
      run: flutter build windows --release

    - name: Create release archive
      run: |
        cd build\windows\x64\runner\Release
        Compress-Archive -Path * -DestinationPath ..\..\..\..\..\jellyfish-windows.zip
        
    - name: Upload Windows build artifact
      uses: actions/upload-artifact@v4
      with:
        name: jellyfish-windows
        path: jellyfish-windows.zip
        retention-days: 30
        
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: jellyfish-windows.zip
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
